In [1]:
# Importar librerías para manipulación y análisis de datos
# -----------------------------------------------------------------------
import pandas as pd
from pandas import DataFrame
import numpy as np
pd.set_option('display.max_columns', None)  # Establece una opción de Pandas para mostrar todas las columnas de un DataFrame.

# Imputación de nulos usando métodos avanzados estadísticos
# -----------------------------------------------------------------------
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt

# establece el estilo del fondo de las gráficas como "whitegrid". Las gráficas tendrán un fondo blanco con líneas de cuadrícula horizontales y verticales.
sns.set_style("whitegrid")

# cambiará el esquema de colores predeterminado de Seaborn a uno más oscuro, adecuado para gráficas con fondos claros. 
sns.set_theme(style="dark")

# establece el estilo en Solarize_Lihgt2. 
plt.style.use('Solarize_Light2')
import mysql.connector

In [2]:
definitivo = pd.read_csv("definitivo.csv", index_col = 0)

In [3]:
df_salario = definitivo[['dailyrate', 'monthlyrate', 'percentsalaryhike', 'hourlyrate', 'employeenumber']]
df_salario

      dailyrate  monthlyrate  percentsalaryhike  hourlyrate  employeenumber
0         684.0       6462.0                 13        51.0           162.0
1         699.0       5678.0                 14        65.0           259.0
2         532.0       4933.0                 11        58.0           319.0
3         359.0      26703.0                 19        82.0             NaN
4        1319.0       7739.0                 12        45.0             NaN
...         ...          ...                ...         ...             ...
1607      616.0      17369.0                 11        41.0             NaN
1608      498.0      13554.0                 12        93.0           966.0
1610      805.0      23163.0                 12        57.0           972.0
1611      903.0       2560.0                 18        41.0             NaN
1613      566.0      24208.0                 13        75.0             NaN

[1571 rows x 5 columns]

In [5]:
df_salario_none = df_salario.replace([np.nan],[None])

In [6]:
lista_tuplas_salario = [tuple(x) for x in df_salario_none.values]
lista_tuplas_salario

[(684.0, 6462.0, 13, 51.0, 162.0),
 (699.0, 5678.0, 14, 65.0, 259.0),
 (532.0, 4933.0, 11, 58.0, 319.0),
 (359.0, 26703.0, 19, 82.0, None),
 (1319.0, 7739.0, 12, 45.0, None),
 (117.0, 2437.0, 11, 58.0, 1900.0),
 (1435.0, 2354.0, 11, 99.0, 81.0),
 (635.0, 24532.0, 25, 99.0, 387.0),
 (1276.0, 5626.0, 16, 91.0, None),
 (840.0, 3735.0, 17, 64.0, 999.0),
 (247.0, 20284.0, 22, 55.0, 1035.0),
 (1369.0, 18235.0, 12, 68.0, None),
 (201.0, 3376.0, 12, 99.0, None),
 (1360.0, 16280.0, 12, 49.0, 58.0),
 (692.0, 13339.0, 11, 61.0, None),
 (1398.0, 13022.0, 14, 79.0, 558.0),
 (286.0, 25761.0, 12, 31.0, 825.0),
 (1402.0, 24097.0, 23, 69.0, None),
 (819.0, 26312.0, 11, 48.0, None),
 (884.0, 25800.0, 13, 80.0, None),
 (1238.0, 3395.0, 23, 74.0, 1712.0),
 (515.0, 15146.0, 12, 98.0, 73.0),
 (1223.0, 8202.0, 13, 59.0, None),
 (202.0, 12982.0, 11, 33.0, 820.0),
 (928.0, 2823.0, 14, 56.0, None),
 (607.0, 23457.0, 20, 66.0, None),
 (266.0, 25846.0, 15, 57.0, None),
 (429.0, 2323.0, 11, 53.0, 1294.0),
 (589.0, 22949.0, 12, 79.0, None),
 (None, 12313.0, 14, 87.0, 1774.0),
 (None, 26458.0, 13, 81.0, 1815.0),
 (1180.0, 13084.0, 23, 84.0, 1993.0),
 (1282.0, 10735.0, 11, 58.0, 32.0),
 (776.0, 23016.0, 14, 32.0, 100.0),
 (665.0, 12482.0, 14, 41.0, None),
 (526.0, 2137.0, 25, 92.0, 244.0),
 (1034.0, 7744.0, 22, 80.0, 327.0),
 (1403.0, 20251.0, 11, 47.0, 373.0),
 (1499.0, 2845.0, 19, 80.0, None),
 (580.0, 23772.0, 21, 48.0, 729.0),
 (859.0, 19124.0, 12, 98.0, 830.0),
 (263.0, 3119.0, 13, 59.0, None),
 (1376.0, 13938.0, 13, 65.68246065041718, 981.0),
 (885.0, 8269.0, 16, 43.0, 1042.0),
 (1003.0, 21029.0, 23, 74.0, 1080.0),
 (1321.0, 7636.0, 15, 86.0, 1995.0),
 (None, 25796.0, 20, 30.0, 145.0),
 (394.0, 19494.0, 12, 92.0, 158.0),
 (1372.0, 15881.0, 12, 42.0, 391.0),
 (None, 24624.0, 11, 65.0, 436.0),
 (1333.0, 16292.0, 13, 80.0, None),
 (228.0, 11380.0, 12, 51.0, 1527.0),
 (737.0, 21530.0, 17, 55.0, None),
 (823.0, 22539.0, 13, 81.0, 1866.0),
 (667.0, 26236.0, 21, 57.0, 2026.0),
 (301.0, 10436.0, 24, 88.0, None),
 (573.0, 15717.0, 12, 79.0, 107.0),
 (None, 5549.0, 14, 96.0, 170.0),
 (1329.0, 14590.0, 14, 47.0, None),
 (630.0, 8552.0, 11, 67.0, 215.0),
 (None, 9945.0, 16, 62.0, 304.0),
 (1063.0, 23866.0, 15, 72.0, 529.0),
 (1017.0, 19368.0, 13, 82.0, 691.0),
 (1296.0, 5335.0, 23, 66.22234343852926, 692.0),
 (939.0, 4161.0, 18, 65.00927227491015, 1005.0),
 (1355.0, 22245.0, 14, 78.0, 1024.0),
 (1448.0, 11737.0, 18, 53.0, 1039.0),
 (200.0, 7744.0, 25, 32.0, 1225.0),
 (1202.0, 13888.0, 20, 89.0, 1375.0),
 (404.0, 6163.0, 11, 98.0, None),
 (208.0, 12250.0, 12, 52.0, None),
 (813.0, 21981.0, 15, 50.0, None),
 (465.0, 11652.0, 19, 41.0, 1661.0),
 (1189.0, 9867.0, 15, 90.0, 1668.0),
 (None, 13637.0, 18, 79.0, 1698.0),
 (1001.0, 19271.0, 12, 92.0, None),
 (1394.0, 18115.0, 16, 58.0, 1937.0),
 (161.0, 15471.0, 25, 42.0, 2017.0),
 (288.0, 15830.0, 19, 99.0, 117.0),
 (682.0, 24409.0, 13, 37.0, 131.0),
 (1354.0, 5615.0, 12, 45.0, 153.0),
 (147.0, 3465.0, 12, 94.0, None),
 (119.0, 9647.0, 12, 76.0, 307.0),
 (1413.0, 6599.0, 14, 42.0, None),
 (452.0, 18938.0, 14, 81.0, 374.0),
 (334.0, 15896.0, 19, 88.0, None),
 (1132.0, 10942.0, 17, 48.0, None),
 (None, 15682.0, 14, 92.0, None),
 (982.0, 4345.0, 11, 59.0, None),
 (480.0, 4156.0, 12, 31.0, 524.0),
 (1099.0, 9314.0, 15, 88.0, 569.0),
 (672.0, 9129.0, 16, 78.0, 899.0),
 (1379.0, 6759.0, 19, 64.0, None),
 (583.0, 6975.0, 11, 57.0, 1014.0),
 (1492.0, 26542.0, 20, 61.0, None),
 (1050.0, 17970.0, 13, 65.0, 1117.0),
 (117.0, 6311.0, 13, 60.0, 1238.0),
 (469.0, 9256.0, 12, 46.0, None),
 (None, 2493.0, 16, 94.0, 1277.0),
 (237.0, 19196.0, 24, 83.0, None),
 (1440.0, 4944.0, 25, 55.0, 1541.0),
 (1291.0, 3525.0, 24, 65.0, 1666.0),
 (1157.0, 11912.0, 14, 57.0, 1696.0),
 (1336.0, 7129.0, 13, 100.0, 1805.0),
 (1224.0, 13583.0, 12, 91.0, None),
 (735.0, 26496.0, 15, 86.0, 1932.0),
 (None, 24032.0, 19, 48.0, 2016.0),
 (1389.0, 10195.0, 11, 51.0, 20.0),
 (638.0, 3142.0, 13, 40.0, None),
 (1240.0, 13982.0, 19, 48.0, 184.0),
 (194.0, 10901.0, 18, 60.0, 206.0),
 (1339.0, 8053.0, 12, 41.0, 228.0),
 (111.0, 11012.0, 11, 66.0, 239.0),
 (None, 14074.0, 17, 45.0, 256.0),
 (1469.0, 15736.0, 16, 81.0, None),
 (470.0, 23687.0, 13, 84.0, 339.0),
 (1232.0, 5100.0, 15, 96.0, 406.0),
 (1249.0, 20308.0, 18, 97.0, None),
 (117.0, 5355.0, 14, 99.0, 429.0),
 (798.0, 14034.0, 24, 48.0, None),
 (672.0, 21141.0, 15, 54.0, 444.0),
 (549.0, 9278.0, 14, 75.0, 452.0),
 (570.0, 5431.0, 13, 30.0, 456.0),
 (1232.0, 25713.0, 14, 39.0, None),
 (541.0, 7246.0, 11, 48.0, 481.0),
 (164.0, 3809.0, 13, 61.0, 513.0),
 (1117.0, 9873.0, 23, 83.0, 597.0),
 (619.0, 18659.0, 11, 85.0, 600.0),
 (319.0, 6950.0, 21, 56.0, None),
 (956.0, 22087.0, 12, 78.0, 630.0),
 (1245.0, 2125.0, 17, 58.0, 638.0),
 (1397.0, 7660.0, 12, 42.0, 683.0),
 (527.0, 5207.0, 13, 63.0, 780.0),
 (213.0, 25995.0, 11, 49.0, 817.0),
 (None, 20206.0, 18, 72.0, 901.0),
 (527.0, 22477.0, 11, 51.0, 944.0),
 (882.0, 6812.0, 13, 65.92578048363522, 984.0),
 (330.0, 24608.0, 18, 65.0, 1088.0),
 (406.0, 15596.0, 12, 67.48288428010049, 1124.0),
 (217.0, 23238.0, 20, 78.0, None),
 (481.0, 2447.0, 12, 44.0, 1167.0),
 (669.0, 25755.0, 20, 97.0, 1184.0),
 (1465.0, 9369.0, 21, 63.0, None),
 (685.0, 23474.0, 14, 85.0, None),
 (1062.0, 17198.0, 19, 96.0, 1252.0),
 (1099.0, 8751.0, 11, 88.0, 1267.0),
 (177.0, 25592.0, 15, 37.0, 1278.0),
 (1199.0, 17477.0, 14, 92.0, 1288.0),
 (648.0, 21833.0, 11, 56.0, None),
 (412.0, 17334.0, 13, 94.0, 1307.0),
 (282.0, 6992.0, 14, 58.0, 1336.0),
 (770.0, 17588.0, 11, 84.0, 1352.0),
 (601.0, 12023.0, 14, 53.0, 1360.0),
 (855.0, 18706.0, 11, 54.0, None),
 (332.0, 9769.0, 13, 51.0, 1419.0),
 (1326.0, 15891.0, 18, 81.0, 1478.0),
 (748.0, 16458.0, 13, 74.0, 1480.0),
 (405.0, 2721.0, 24, 93.0, None),
 (790.0, 7815.0, 23, 40.0, 1489.0),
 (1050.0, 24456.0, 20, 87.0, 1520.0),
 (971.0, 12288.0, 14, 64.0, 1535.0),
 (1370.0, 16213.0, 18, 87.0, 1586.0),
 (750.0, 25348.0, 17, 46.0, 1596.0),
 (880.0, 10414.0, 24, 36.0, 1667.0),
 (678.0, 20338.0, 12, 35.0, 1701.0),
 (1179.0, 6069.0, 17, 73.0, 1706.0),
 (350.0, 22577.0, 22, 52.0, None),
 (1266.0, 6060.0, 13, 63.0, None),
 (574.0, 16873.0, 17, 30.0, 1971.0),
 (189.0, 25811.0, 18, 71.0, None),
 (None, 14811.0, 12, 37.0, 1976.0),
 (692.0, 26849.0, 11, 73.0, 1985.0),
 (310.0, 3666.0, 11, 72.0, 2032.0),
 (722.0, 8828.0, 11, 60.0, 2056.0),
 (1219.0, 22021.0, 16, 78.0, None),
 (994.0, 2975.0, 15, 37.0, None),
 (721.0, 10781.0, 23, 58.0, 57.0),
 (853.0, 11031.0, 22, 71.0, None),
 (427.0, 10877.0, 22, 67.43059044597997, 78.0),
 (852.0, 15998.0, 12, 55.0, 104.0),
 (669.0, 13596.0, 16, 64.0, 118.0),
 (1334.0, 19760.0, 12, 63.0, 121.0),
 (1093.0, 24301.0, 16, 87.0, 125.0),
 (None, 11439.0, 13, 94.0, None),
 (967.0, 15589.0, 14, 43.0, 207.0),
 (465.0, 4609.0, 12, 56.0, 227.0),
 (989.0, 6499.0, 14, 46.0, 253.0),
 (1195.0, 20462.0, 23, 65.0, 264.0),
 (1045.0, 25812.0, 11, 32.0, 291.0),
 (829.0, 20925.0, 22, 88.0, 292.0),
 (663.0, 10056.0, 14, 47.0, 306.0),
 (319.0, 2539.0, 17, 41.0, None),
 (1300.0, 24447.0, 17, 62.0, 335.0),
 (1105.0, 6927.0, 15, 47.0, None),
 (906.0, 16985.0, 14, 91.0, 420.0),
 (849.0, 26707.0, 17, 81.0, 421.0),
 (1275.0, 11934.0, 13, 64.0, 441.0),
 (1218.0, 8213.0, 14, 52.0, 531.0),
 (422.0, 3854.0, 11, 41.0, 549.0),
 (1398.0, 2890.0, 11, 69.0, 567.0),
 (1274.0, 14394.0, 25, 65.43544975781255, 581.0),
 (1076.0, 3164.0, 11, 70.0, 702.0),
 (1207.0, 3297.0, 11, 74.0, 716.0),
 (430.0, 21146.0, 15, 80.0, 772.0),
 (933.0, 11806.0, 13, 98.0, 836.0),
 (1184.0, 5860.0, 18, 43.0, 840.0),
 (None, 8842.0, 16, 42.0, 844.0),
 (586.0, 21816.0, 22, 48.0, None),
 (890.0, 19028.0, 22, 81.0, 867.0),
 (379.0, 8891.0, 14, 48.0, 889.0),
 (1425.0, 4821.0, 17, 68.0, 924.0),
 (1188.0, 24406.0, 13, 45.0, None),
 (938.0, 12287.0, 21, 79.0, None),
 (1053.0, 13829.0, 15, 70.0, 976.0),
 (722.0, 20489.0, 11, 38.0, 992.0),
 (248.0, 14039.0, 15, 42.0, 1002.0),
 (796.0, 15669.0, 11, 51.0, 1073.0),
 (174.0, 11879.0, 17, 56.0, 1138.0),
 (408.0, 11162.0, 13, 45.0, None),
 (None, 26342.0, 13, 54.0, 1192.0),
 (977.0, 9961.0, 13, 56.0, 1196.0),
 (536.0, 21708.0, 14, 82.0, None),
 (135.0, 22534.0, 13, 46.0, None),
 (1476.0, 16392.0, 11, 55.0, 1315.0),
 (587.0, 8935.0, 19, 57.0, 1324.0),
 (495.0, 26582.0, 13, 66.12679513022508, 1334.0),
 (523.0, 22455.0, 13, 98.0, 1346.0),
 (507.0, 23553.0, 12, 66.0, 1356.0),
 (1055.0, 22456.0, 21, 76.0, 1423.0),
 (1445.0, 8931.0, 11, 100.0, 1459.0),
 (218.0, 25178.0, 11, 55.0, None),
 (447.0, 19764.0, 12, 39.0, 1472.0),
 (829.0, 11929.0, 14, 71.0, 1485.0),
 (1029.0, 21195.0, 19, 91.0, None),
 (674.0, 3031.0, 17, 47.0, 1543.0),
 (None, 18611.0, 14, 40.0, 1547.0),
 (538.0, 20933.0, 12, 66.0, 1553.0),
 (740.0, 5323.0, 11, 64.0, 1562.0),
 (1245.0, 12355.0, 11, 80.0, 1582.0),
 (1234.0, 20689.0, 15, 41.0, 1606.0),
 (170.0, 10302.0, 15, 76.0, None),
 (1130.0, 19332.0, 12, 66.0, 1658.0),
 (584.0, 18685.0, 25, 91.0, 1665.0),
 (918.0, 15869.0, 12, 35.0, None),
 (792.0, 8989.0, 15, 77.0, 1737.0),
 (611.0, 4349.0, 14, 88.0, None),
 (None, 6194.0, 15, 90.0, None),
 (1383.0, 25949.0, 13, 90.0, 1790.0),
 (867.0, 6076.0, 19, 90.0, None),
 (None, 22128.0, 21, 92.0, 1823.0),
 (574.0, 7003.0, 13, 40.0, None),
 (706.0, 19989.0, 14, 82.0, 1857.0),
 (728.0, 7018.0, 21, 36.0, 1864.0),
 (311.0, 18624.0, 11, 89.0, 1881.0),
 (556.0, 23888.0, 13, 93.0, 1888.0),
 (937.0, 6770.0, 21, 32.0, 1950.0),
 (1125.0, 5771.0, 21, 48.0, None),
 (1224.0, 13586.0, 11, 55.0, 1962.0),
 (119.0, 25098.0, 12, 77.0, 1975.0),
 (444.0, 4258.0, 14, 92.0, 1986.0),
 (911.0, 4077.0, 13, 76.0, None),
 (None, 17231.0, 18, 98.0, 2000.0),
 (585.0, 19788.0, 15, 67.64790019779859, None),
 (None, 24907.0, 23, 61.0, 2.0),
 (1392.0, 23159.0, 11, 56.0, 5.0),
 (1005.0, 11864.0, 13, 79.0, None),
 (None, 8787.0, 21, 44.0, None),
 (1299.0, 16577.0, 13, 94.0, None),
 (None, 21173.0, 11, 48.0, 35.0),
 (655.0, 9528.0, 22, 48.0, 76.0),
 (746.0, 20682.0, 23, 61.0, 98.0),
 (632.0, 8423.0, 22, 71.0, 120.0),
 (658.0, 22887.0, 24, 66.0, 147.0),
 (1467.0, 22952.0, 14, 92.0, 154.0),
 (1312.0, 22310.0, 25, 96.0, 159.0),
 (750.0, 15480.0, 13, 95.0, 160.0),
 (249.0, 20739.0, 18, 76.0, 163.0),
 (802.0, 21196.0, 13, 96.0, 176.0),
 (1355.0, 8916.0, 23, 61.0, 177.0),
 (689.0, 22812.0, 17, 35.0, 195.0),
 (1395.0, 8504.0, 11, 54.0, 202.0),
 (1436.0, 16047.0, 20, 34.0, 205.0),
 (1496.0, 26283.0, 13, 41.0, None),
 (1480.0, 15062.0, 12, 30.0, None),
 (None, 4673.0, 13, 64.68696953992892, 252.0),
 (313.0, 7192.0, 18, 98.0, 258.0),
 (894.0, 11781.0, 16, 99.0, 260.0),
 (290.0, 22977.0, 12, 65.0, 267.0),
 (1084.0, 4185.0, 18, 54.0, None),
 (1002.0, 23793.0, 15, 92.0, 275.0),
 (1242.0, 12916.0, 14, 90.0, 293.0),
 (1052.0, 16840.0, 12, 57.0, 302.0),
 (944.0, 9096.0, 14, 92.0, 314.0),
 (465.0, 21509.0, 20, 39.0, None),
 (771.0, 21030.0, 18, 79.0, 329.0),
 (1416.0, 5949.0, 19, 49.0, None),
 (1327.0, 19682.0, 18, 39.0, 361.0),
 (488.0, 14977.0, 12, 75.0, 363.0),
 (1385.0, 7501.0, 14, 79.0, None),
 (666.0, 10268.0, 12, 88.0, 376.0),
 (1315.0, 19100.0, 18, 71.0, 381.0),
 (442.0, 20260.0, 18, 44.0, 388.0),
 (147.0, 15972.0, 19, 37.0, 389.0),
 (950.0, 8450.0, 12, 48.0, 401.0),
 (218.0, 12241.0, 11, 100.0, 416.0),
 (None, 10675.0, 19, 33.0, 430.0),
 (691.0, 7143.0, 12, 73.0, 438.0),
 (1018.0, 10557.0, 16, 74.0, None),
 (None, 4317.0, 14, 46.0, 446.0),
 (559.0, 6227.0, 11, 82.0, 448.0),
 (318.0, 4759.0, 11, 77.0, 454.0),
 (1130.0, 3415.0, 18, 56.0, 458.0),
 (144.0, 11866.0, 14, 39.0, None),
 (1319.0, 17001.0, 13, 51.0, None),
 (933.0, 20156.0, 17, 57.0, 476.0),
 (1171.0, 22495.0, 13, 46.0, 483.0),
 (143.0, 9558.0, 18, 56.0, 488.0),
 (1178.0, 14862.0, 11, 87.0, 500.0),
 (1107.0, 26914.0, 12, 95.0, None),
 (906.0, 18256.0, 11, 86.0, None),
 (645.0, 19566.0, 16, 49.0, 534.0),
 (1485.0, 26314.0, 14, 87.0, None),
 (1116.0, 7181.0, 14, 49.0, None),
 (1276.0, 14295.0, 12, 72.0, 586.0),
 (163.0, 19658.0, 14, 37.0, 595.0),
 (561.0, 16177.0, 19, 61.0, None),
 (426.0, 22808.0, 11, 58.0, 608.0),
 (509.0, 2112.0, 17, 62.0, 616.0),
 (258.0, 19921.0, 12, 74.0, 621.0),
 (525.0, 6219.0, 22, 66.0, 653.0),
 (None, 19627.0, 13, 72.0, 663.0),
 (238.0, 7507.0, 20, 34.0, 682.0),
 (482.0, 9606.0, 15, 36.0, None),
 (397.0, 6729.0, 15, 88.0, None),
 (243.0, 7791.0, 20, 46.0, None),
 (806.0, 18959.0, 18, 76.0, 710.0),
 (1442.0, 17654.0, 14, 46.0, 717.0),
 (408.0, 20978.0, 11, 80.0, 721.0),
 (929.0, 21703.0, 12, 55.0, 722.0),
 (827.0, 19383.0, 13, 33.0, 724.0),
 (None, 6009.0, 11, 65.61685759123075, 725.0),
 (1018.0, 19373.0, 15, 39.0, None),
 (703.0, 11825.0, 12, 42.0, 728.0),
 (294.0, 4809.0, 21, 32.0, 733.0),
 (314.0, 19562.0, 12, 59.0, 734.0),
 (654.0, 3872.0, 13, 67.0, None),
 (427.0, 20335.0, 14, 63.0, 742.0),
 (501.0, 25275.0, 23, 99.0, 747.0),
 (None, 20420.0, 11, 81.0, 762.0),
 (954.0, 12388.0, 13, 46.0, 783.0),
 (1434.0, 14229.0, 15, 76.0, 789.0),
 (657.0, 25549.0, 12, 66.0, 793.0),
 (240.0, 26085.0, 12, 75.0, 803.0),
 (791.0, 9931.0, 24, 38.0, None),
 (570.0, 16225.0, 13, 66.0, 809.0),
 (676.0, 23361.0, 15, 35.0, 823.0),
 (None, 23779.0, 24, 81.0, None),
 (436.0, 21519.0, 16, 37.0, 842.0),
 (760.0, 3698.0, 20, 81.0, None),
 (None, 20898.0, 14, 88.0, None),
 (661.0, 7508.0, 13, 61.0, 913.0),
 (1085.0, 17725.0, 13, 57.0, 927.0),
 (154.0, 11737.0, 15, 41.0, 941.0),
 (1283.0, 11148.0, 12, 52.0, 956.0),
 (616.0, 17369.0, 11, 41.0, None),
 (498.0, 13554.0, 12, 93.0, 966.0),
 (530.0, 5518.0, 11, 51.0, 967.0),
 (805.0, 23163.0, 12, 57.0, 972.0),
 (903.0, 2560.0, 18, 41.0, None),
 (1229.0, 25952.0, 13, 84.0, 990.0),
 (566.0, 24208.0, 13, 64.76225461114875, None),
 (1441.0, 13943.0, 11, 56.0, 1013.0),
 (153.0, 17802.0, 12, 73.0, 1015.0),
 (1066.0, 3334.0, 12, 32.0, 1018.0),
 (135.0, 12992.0, 14, 62.0, 1034.0),
 (145.0, 24920.0, 12, 95.0, None),
 (1109.0, 11135.0, 12, 69.0, 1046.0),
 (124.0, 23537.0, 12, 38.0, 1050.0),
 (300.0, 22217.0, 14, 74.0, None),
 (444.0, 17323.0, 15, 40.0, 1074.0),
 (1366.0, 12355.0, 12, 72.0, 1082.0),
 (857.0, 7909.0, 13, 59.0, 1097.0),
 (1204.0, 10333.0, 22, 86.0, 1100.0),
 (827.0, 3129.0, 22, 54.0, 1101.0),
 (1219.0, 4605.0, 15, 32.0, 1106.0),
 (770.0, 5569.0, 14, 65.67230179030103, 1119.0),
 (950.0, 8039.0, 17, 93.0, None),
 (1082.0, 11535.0, 11, 83.0, 1126.0),
 (203.0, 13547.0, 11, 84.0, None),
 (1308.0, 17544.0, 14, 44.0, 1128.0),
 (718.0, 17689.0, 15, 79.0, None),
 (593.0, 13782.0, 17, 88.0, None),
 (1384.0, 13421.0, 22, 82.0, 1177.0),
 (819.0, 19588.0, 18, 44.0, 1182.0),
 (1223.0, 18640.0, 18, 50.0, 1201.0),
 (1361.0, 21026.0, 15, 94.0, 1218.0),
 (1146.0, 4905.0, 12, 66.80968913343669, 1220.0),
 (None, 6865.0, 14, 60.0, None),
 (853.0, 11309.0, 13, 49.0, 1224.0),
 (None, 10893.0, 18, 52.0, None),
 (1316.0, 2338.0, 14, 38.0, 1235.0),
 (363.0, 4235.0, 21, 65.8010305826486, 1237.0),
 (1103.0, 14377.0, 14, 42.0, None),
 (920.0, 18625.0, 14, 96.0, 1255.0),
 (694.0, 3423.0, 14, 64.94366921572372, 1264.0),
 (1429.0, 20002.0, 12, 67.0, 1283.0),
 (531.0, 20364.0, 14, 56.0, 1293.0),
 (621.0, 14075.0, 11, 73.0, 1295.0),
 (806.0, 17285.0, 13, 39.0, None),
 (604.0, 11693.0, 15, 56.0, None),
 (325.0, 5747.0, 12, 63.0, None),
 (1030.0, 21534.0, 19, 64.0, None),
 (524.0, 13352.0, 11, 32.0, 1322.0),
 (943.0, 5494.0, 11, 86.0, 1344.0),
 (1009.0, 19461.0, 15, 31.0, 1355.0),
 (607.0, 2261.0, 16, 83.0, 1362.0),
 (817.0, 10846.0, 12, 60.0, 1369.0),
 (None, 9277.0, 17, 85.0, None),
 (None, 17491.0, 13, 86.0, 1377.0),
 (930.0, 20003.0, 14, 73.0, 1402.0),
 (1147.0, 16616.0, 14, 31.0, 1408.0),
 (652.0, 23577.0, 12, 100.0, 1417.0),
 (337.0, 22930.0, 12, 84.0, 1421.0),
 (971.0, 5652.0, 19, 54.0, 1422.0),
 (1136.0, 12414.0, 13, 81.0, 1424.0),
 (663.0, 23099.0, 11, 81.0, None),
 (326.0, 8386.0, 18, 31.0, None),
 (377.0, 15986.0, 11, 52.0, 1457.0),
 (1038.0, 19863.0, 18, 95.0, 1460.0),
 (1490.0, 20948.0, 14, 35.0, 1484.0),
 (1246.0, 23757.0, 14, 77.0, 1497.0),
 (224.0, 7568.0, 13, 100.0, 1522.0),
 (441.0, 7288.0, 13, 39.0, 1544.0),
 (898.0, 17381.0, 21, 38.0, None),
 (None, 13693.0, 14, 96.0, None),
 (607.0, 14618.0, 16, 78.0, 1572.0),
 (1313.0, 3549.0, 14, 31.0, 1608.0),
 (1015.0, 23447.0, 14, 50.0, 1611.0),
 (None, 24162.0, 15, 52.0, 1612.0),
 (426.0, 17000.0, 13, 42.0, 1615.0),
 (1387.0, 3835.0, 13, 76.0, None),
 (1302.0, 16290.0, 11, 65.8287650351406, 1619.0),
 (1329.0, 5388.0, 19, 59.0, 1635.0),
 (602.0, 10503.0, 11, 37.0, 1642.0),
 (772.0, 4973.0, 17, 77.0, 1653.0),
 (809.0, 22384.0, 14, 36.0, None),
 (None, 11740.0, 11, 95.0, 1691.0),
 (786.0, 11925.0, 20, 76.0, 1693.0),
 (921.0, 14810.0, 19, 96.0, 1703.0),
 (530.0, 7439.0, 15, 51.0, None),
 (717.0, 9697.0, 14, 34.0, 1727.0),
 (1370.0, 5151.0, 16, 49.0, 1728.0),
 (1312.0, 26427.0, 16, 78.0, 1745.0),
 (979.0, 3088.0, 11, 94.0, 1754.0),
 (1283.0, 10697.0, 15, 62.0, 1756.0),
 (953.0, 17674.0, 14, 65.0, 1764.0),
 (244.0, 5033.0, 13, 97.0, 1778.0),
 (196.0, 13402.0, 14, 91.0, None),
 (303.0, 13492.0, 18, 84.0, 1797.0),
 (1180.0, 24442.0, 14, 90.0, 1804.0),
 (1092.0, 2739.0, 14, 64.0, 1816.0),
 (261.0, 10842.0, 22, 66.0, 1821.0),
 (589.0, 19665.0, 22, 67.0, None),
 (1422.0, 19246.0, 20, 92.0, 1849.0),
 (None, 14011.0, 21, 64.0, 1869.0),
 (1137.0, 18991.0, 11, 98.0, None),
 (511.0, 26997.0, 14, 89.0, 1898.0),
 (1396.0, 14842.0, 13, 83.0, 1911.0),
 (1096.0, 7102.0, 18, 61.0, None),
 (None, 19255.0, 12, 42.0, 1927.0),
 (1169.0, 2125.0, 18, 64.0, 1934.0),
 (1239.0, 22914.0, 18, 39.0, 1951.0),
 (157.0, 20006.0, 13, 95.0, 1952.0),
 (954.0, 5099.0, 14, 44.0, 1965.0),
 (754.0, 21075.0, 11, 63.0, 1967.0),
 (1303.0, 18079.0, 20, 64.70999116385615, None),
 (697.0, 26862.0, 20, 40.0, 1979.0),
 (1395.0, 18698.0, 19, 48.0, 2008.0),
 (501.0, 21653.0, 13, 95.0, 2009.0),
 (116.0, 5340.0, 13, 52.0, 2014.0),
 (557.0, 12695.0, 19, 94.0, None),
 (582.0, 5640.0, 23, 60.0, 2034.0),
 (704.0, 8978.0, 21, 95.0, 2035.0),
 (None, 5982.0, 11, 100.0, None),
 (613.0, 21457.0, 15, 42.0, 2062.0),
 (419.0, 21293.0, 11, 53.0, 28.0),
 (477.0, 2094.0, 14, 42.0, None),
 (1211.0, 20445.0, 21, 98.0, 62.0),
 (857.0, 12888.0, 13, 91.0, 199.0),
 (505.0, 6420.0, 25, 64.0, 343.0),
 (269.0, 8007.0, 11, 56.0, 351.0),
 (553.0, 23364.0, 11, 74.0, 428.0),
 (1296.0, 18264.0, 13, 62.0, 464.0),
 (1277.0, 24619.0, 12, 56.0, None),
 (302.0, 20364.0, 15, 75.0, None),
 (427.0, 8861.0, 15, 73.0, 731.0),
 (975.0, 23398.0, 19, 55.0, 764.0),
 (621.0, 10084.0, 11, 31.0, None),
 (1318.0, 5594.0, 14, 66.0, 851.0),
 (249.0, 17783.0, 22, 35.0, 903.0),
 (881.0, 4544.0, 11, 98.0, 905.0),
 (1137.0, 19170.0, 25, 51.0, 942.0),
 (466.0, 7060.0, 16, 65.0, 1026.0),
 (945.0, 5083.0, 13, 82.0, None),
 (509.0, 18863.0, 13, 43.0, 1085.0),
 (1376.0, 2326.0, 14, 91.0, None),
 (469.0, 14399.0, 17, 35.0, 1109.0),
 (994.0, 15322.0, 19, 87.0, 1118.0),
 (433.0, 6004.0, 13, 37.0, 1152.0),
 (991.0, 22957.0, 12, 44.0, None),
 (482.0, 2690.0, 11, 87.0, 1350.0),
 (1083.0, 3173.0, 14, 96.0, 1514.0),
 (136.0, 22074.0, 13, 32.0, 1523.0),
 (333.0, 24450.0, 13, 88.0, 1539.0),
 (685.0, 23037.0, 21, 60.0, None),
 (1462.0, 4658.0, 11, 38.0, 1588.0),
 (722.0, 22102.0, 14, 84.0, 1617.0),
 (None, 17119.0, 11, 48.0, 1719.0),
 (1277.0, 5596.0, 12, 74.0, None),
 (1131.0, 23844.0, 19, 77.0, 1870.0),
 (300.0, 17312.0, 11, 56.0, 2031.0),
 (1023.0, 13243.0, 14, 63.0, 2065.0),
 (153.0, 12682.0, 12, 49.0, 15.0),
 (1065.0, 10034.0, 20, 72.0, 60.0),
 (1115.0, 2689.0, 18, 51.0, None),
 (1195.0, 22656.0, 13, 95.0, 85.0),
 (1316.0, 9752.0, 13, 83.0, None),
 (665.0, 22673.0, 19, 60.0, 346.0),
 (1479.0, 26767.0, 20, 84.0, 384.0),
 (304.0, 20750.0, 16, 92.0, 498.0),
 (1368.0, 4386.0, 11, 64.43026986413413, 551.0),
 (828.0, 8346.0, 13, 77.0, 604.0),
 (799.0, 23848.0, 17, 59.0, None),
 (142.0, 24666.0, 13, 69.0, 626.0),
 (446.0, 15701.0, 12, 65.0, None),
 (691.0, 21630.0, 11, 89.0, None),
 (1246.0, 7999.0, 11, 99.0, 644.0),
 (254.0, 22794.0, 13, 83.0, 649.0),
 (1410.0, 16673.0, 20, 71.0, 714.0),
 (883.0, 22807.0, 23, 32.0, 781.0),
 (304.0, 18686.0, 22, 60.0, None),
 (121.0, 7530.0, 11, 86.0, 804.0),
 (950.0, 18869.0, 21, 59.0, None),
 (1343.0, 17852.0, 11, 53.0, 856.0),
 (827.0, 20161.0, 13, 84.0, 998.0),
 (1107.0, 26968.0, 22, 93.0, 1120.0),
 (490.0, 17940.0, 14, 61.0, 1143.0),
 (1400.0, 5829.0, 20, 70.0, None),
 (1179.0, 12449.0, 12, 78.0, None),

In [22]:
cnx = mysql.connector.connect(user = "root",
                              password = "AlumnaAdalab",
                              host = "127.0.0.1",
                              database = "abc_proyecto")#Nuesta base de datos de mysql
#Nos permite enviar informacion atraves de la conexciosm
mycursor = cnx.cursor()


#Escribimos la query aqui
#¡¡¡El ORDEN IMPORTA!!! --> El primer dato debe ser el primer elemento de la lista de tuplas
#sql_proyecto1 = "INSERT INTO salario (dailyrate, monthlyrate, percentsalaryhike, hourlyrate, employeenumber) VALUES (%s, %s, %s, %s,%s)" 
sql_proyecto1 = "INSERT INTO salario (dailyrate, monthlyrate, percentsalaryhike, hourlyrate, employeenumber) VALUES (%s, %s, %s, %s, %s)"
try:
    mycursor.executemany(sql_proyecto1, lista_tuplas_salario)
    cnx.commit()
    print(mycursor.rowcount,"registros insertados")
except Exception as e:
    print("Ha habido un error en la inserción:", e)

1571 registros insertados

In [9]:
df_abandono_satisfaccion = definitivo[['attrition', 'environmentsatisfaction', 'environmentsatisfaction_cat', 'jobinvolvement', 'jobinvolvement_cat', 'jobsatisfaction','relationshipsatisfaction', 'relationshipsatisfaction_cat', 'worklifebalance', 'worklifebalance_cat', 'employeenumber']]
df_abandono_satisfaccion

,attrition,environmentsatisfaction,environmentsatisfaction_cat,jobinvolvement,jobinvolvement_cat,jobsatisfaction,relationshipsatisfaction,relationshipsatisfaction_cat,worklifebalance,worklifebalance_cat,employeenumber
0,No,1.00000,nothing,3,involved,3,3,medium,3.000000,medium,162.0
1,No,3.00000,medium,2,little involved,3,1,nothing,3.000000,medium,259.0
2,No,3.00000,medium,3,involved,4,4,maximun,2.764403,unknown,319.0
3,No,1.00000,nothing,3,involved,3,2,little,2.752658,unknown,NaN
4,No,1.00000,nothing,4,very involved,1,4,maximun,3.000000,medium,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1607,No,4.00000,maximun,3,involved,4,3,medium,1.000000,nothing,NaN
1608,No,3.00000,medium,3,involved,1,3,medium,4.000000,maximun,966.0
1610,No,3.00000,medium,3,involved,2,2,little,2.000000,little,972.0
1611,No,2.80337,unknown,4,very involved,3,4,maximun,3.000000,medium,NaN
1613,No,4.00000,maximun,3,involved,3,2,little,3.000000,medium,NaN

In [11]:
df_abandono_none = df_abandono_satisfaccion.replace([np.nan],[None] )

In [12]:
lista_tuplas_abandono = [tuple(x) for x in df_abandono_none.values]
lista_tuplas_abandono

[('No', 1.0, 'nothing', 3, 'involved', 3, 3, 'medium', 3.0, 'medium', 162.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  1,
  'nothing',
  3.0,
  'medium',
  259.0),
 ('No',
  3.0,
  'medium',
  3,
  'involved',
  4,
  4,
  'maximun',
  2.7644027178413038,
  'unknown',
  319.0),
 ('No',
  1.0,
  'nothing',
  3,
  'involved',
  3,
  2,
  'little',
  2.752658171960187,
  'unknown',
  None),
 ('No',
  1.0,
  'nothing',
  4,
  'very involved',
  1,
  4,
  'maximun',
  3.0,
  'medium',
  None),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 2, 'little', 3.0, 'medium', 1900.0),
 ('No', 1.0, 'nothing', 3, 'involved', 1, 4, 'maximun', 2.0, 'little', 81.0),
 ('No', 2.0, 'little', 3, 'involved', 3, 3, 'medium', 3.0, 'medium', 387.0),
 ('No', 2.0, 'little', 3, 'involved', 1, 2, 'little', 3.0, 'medium', None),
 ('No', 1.0, 'nothing', 3, 'involved', 3, 2, 'little', 4.0, 'maximun', 999.0),
 ('No',
  2.0,
  'little',
  1,
  'not involved',
  3,
  2,
  'little',
  3.0,
  'medium',
  1035.0),
 ('No', 4.0, 'maximun', 3, 'involved', 2, 1, 'nothing', 3.0, 'medium', None),
 ('No',
  2.0,
  'little',
  1,
  'not involved',
  3,
  1,
  'nothing',
  3.0,
  'medium',
  None),
 ('Yes', 2.0, 'little', 3, 'involved', 3, 4, 'maximun', 3.0, 'medium', 58.0),
 ('No',
  3.0,
  'medium',
  4,
  'very involved',
  2,
  4,
  'maximun',
  3.0,
  'medium',
  None),
 ('No', 3.0, 'medium', 3, 'involved', 3, 4, 'maximun', 3.0, 'medium', 558.0),
 ('Yes', 4.0, 'maximun', 3, 'involved', 2, 4, 'maximun', 3.0, 'medium', 825.0),
 ('No', 3.0, 'medium', 3, 'involved', 1, 1, 'nothing', 3.0, 'medium', None),
 ('No',
  2.0,
  'little',
  4,
  'very involved',
  1,
  4,
  'maximun',
  3.0,
  'medium',
  None),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  3,
  4,
  'maximun',
  2.752431550580217,
  'unknown',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  4,
  'maximun',
  2.0,
  'little',
  1712.0),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', 73.0),
 ('No', 3.0, 'medium', 3, 'involved', 3, 2, 'little', 3.0, 'medium', None),
 ('No', 3.0, 'medium', 3, 'involved', 4, 3, 'medium', 2.0, 'little', 820.0),
 ('No',
  2.7544379355548583,
  'unknown',
  3,
  'involved',
  4,
  4,
  'maximun',
  2.7662357899013115,
  'unknown',
  None),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  2,
  'little',
  3.0,
  'medium',
  None),
 ('Yes',
  1.0,
  'nothing',
  1,
  'not involved',
  4,
  4,
  'maximun',
  3.0,
  'medium',
  None),
 ('No', 3.0, 'medium', 3, 'involved', 2, 4, 'maximun', 3.0, 'medium', 1294.0),
 ('No', 2.0, 'little', 3, 'involved', 3, 2, 'little', 3.0, 'medium', None),
 ('No', 4.0, 'maximun', 3, 'involved', 3, 3, 'medium', 3.0, 'medium', 1774.0),
 ('No',
  2.664757301331888,
  'unknown',
  3,
  'involved',
  3,
  4,
  'maximun',
  4.0,
  'maximun',
  1815.0),
 ('No', 1.0, 'nothing', 3, 'involved', 3, 2, 'little', 3.0, 'medium', 1993.0),
 ('No', 3.0, 'medium', 3, 'involved', 3, 4, 'maximun', 2.0, 'little', 32.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  1,
  2,
  'little',
  3.0,
  'medium',
  100.0),
 ('No', 1.0, 'nothing', 3, 'involved', 3, 3, 'medium', 3.0, 'medium', None),
 ('No', 2.0, 'little', 3, 'involved', 1, 3, 'medium', 3.0, 'medium', 244.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', 327.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', 373.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  1,
  4,
  'maximun',
  4.0,
  'maximun',
  None),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  1,
  3,
  'medium',
  3.0,
  'medium',
  729.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  3,
  'medium',
  3.0,
  'medium',
  830.0),
 ('No',
  2.7448931354837707,
  'unknown',
  3,
  'involved',
  1,
  3,
  'medium',
  3.0,
  'medium',
  None),
 ('No', 3.0, 'medium', 3, 'involved', 3, 3, 'medium', 4.0, 'maximun', 981.0),
 ('Yes',
  3.0,
  'medium',
  4,
  'very involved',
  1,
  3,
  'medium',
  3.0,
  'medium',
  1042.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  1,
  1,
  'nothing',
  3.0,
  'medium',
  1080.0),
 ('No',
  4.0,
  'maximun',
  3,
  'involved',
  2,
  1,
  'nothing',
  2.75036026975236,
  'unknown',
  1995.0),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  1,
  3,
  'medium',
  2.0,
  'little',
  145.0),
 ('No', 3.0, 'medium', 3, 'involved', 4, 4, 'maximun', 4.0, 'maximun', 158.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 2, 'little', 3.0, 'medium', 391.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  2,
  4,
  'maximun',
  3.0,
  'medium',
  436.0),
 ('No', 4.0, 'maximun', 3, 'involved', 1, 2, 'little', 3.0, 'medium', None),
 ('No', 3.0, 'medium', 3, 'involved', 2, 4, 'maximun', 4.0, 'maximun', 1527.0),
 ('Yes',
  4.0,
  'maximun',
  2,
  'little involved',
  1,
  3,
  'medium',
  2.7677419413239583,
  'unknown',
  None),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  3,
  4,
  'maximun',
  3.0,
  'medium',
  1866.0),
 ('No', 3.0, 'medium', 3, 'involved', 3, 1, 'nothing', 2.0, 'little', 2026.0),
 ('No',
  4.0,
  'maximun',
  1,
  'not involved',
  4,
  1,
  'nothing',
  2.0,
  'little',
  None),
 ('No',
  2.0,
  'little',
  1,
  'not involved',
  4,
  4,
  'maximun',
  3.0,
  'medium',
  107.0),
 ('No', 3.0, 'medium', 3, 'involved', 1, 3, 'medium', 2.0, 'little', 170.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  3,
  'medium',
  4.0,
  'maximun',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  1,
  'nothing',
  2.0,
  'little',
  215.0),
 ('No', 4.0, 'maximun', 3, 'involved', 2, 4, 'maximun', 4.0, 'maximun', 304.0),
 ('No', 2.0, 'little', 3, 'involved', 3, 1, 'nothing', 3.0, 'medium', 529.0),
 ('No',
  2.0,
  'little',
  1,
  'not involved',
  4,
  2,
  'little',
  3.0,
  'medium',
  691.0),
 ('No', 3.0, 'medium', 3, 'involved', 4, 3, 'medium', 1.0, 'nothing', 692.0),
 ('No', 4.0, 'maximun', 3, 'involved', 3, 4, 'maximun', 3.0, 'medium', 1005.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  2,
  'little',
  3.0,
  'medium',
  1024.0),
 ('No',
  4.0,
  'maximun',
  4,
  'very involved',
  4,
  3,
  'medium',
  3.0,
  'medium',
  1039.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 2, 'little', 3.0, 'medium', 1225.0),
 ('No',
  2.637716885106554,
  'unknown',
  4,
  'very involved',
  3,
  2,
  'little',
  3.0,
  'medium',
  1375.0),
 ('No', 3.0, 'medium', 3, 'involved', 4, 4, 'maximun', 4.0, 'maximun', None),
 ('No', 3.0, 'medium', 3, 'involved', 3, 4, 'maximun', 3.0, 'medium', None),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  1,
  3,
  'medium',
  3.0,
  'medium',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  2,
  'little',
  3.0,
  'medium',
  1661.0),
 ('No',
  4.0,
  'maximun',
  3,
  'involved',
  4,
  4,
  'maximun',
  2.7475471190863883,
  'unknown',
  1668.0),
 ('No',
  2.0,
  'little',
  4,
  'very involved',
  2,
  4,
  'maximun',
  2.754066204611481,
  'unknown',
  1698.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  2,
  3,
  'medium',
  3.0,
  'medium',
  None),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  2,
  3,
  'medium',
  3.0,
  'medium',
  1937.0),
 ('No',
  3.0,
  'medium',
  4,
  'very involved',
  4,
  1,
  'nothing',
  3.0,
  'medium',
  2017.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  1,
  'nothing',
  3.0,
  'medium',
  117.0),
 ('No', 4.0, 'maximun', 3, 'involved', 3, 3, 'medium', 2.0, 'little', 131.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  1,
  4,
  'maximun',
  3.0,
  'medium',
  153.0),
 ('Yes', 4.0, 'maximun', 3, 'involved', 4, 4, 'maximun', 2.0, 'little', None),
 ('No', 1.0, 'nothing', 3, 'involved', 3, 3, 'medium', 2.0, 'little', 307.0),
 ('No', 2.0, 'little', 3, 'involved', 4, 4, 'maximun', 3.0, 'medium', None),
 ('No', 4.0, 'maximun', 3, 'involved', 1, 3, 'medium', 3.0, 'medium', 374.0),
 ('No', 4.0, 'maximun', 3, 'involved', 2, 2, 'little', 3.0, 'medium', None),
 ('No',
  3.0,
  'medium',
  4,
  'very involved',
  4,
  1,
  'nothing',
  2.0,
  'little',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  2,
  'little',
  3.0,
  'medium',
  None),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  2,
  3,
  'medium',
  2.765409226942368,
  'unknown',
  None),
 ('No', 2.0, 'little', 3, 'involved', 1, 2, 'little', 1.0, 'nothing', 524.0),
 ('No',
  2.646632434416129,
  'unknown',
  2,
  'little involved',
  3,
  2,
  'little',
  3.0,
  'medium',
  569.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  2,
  1,
  'nothing',
  3.0,
  'medium',
  899.0),
 ('No',
  3.0,
  'medium',
  4,
  'very involved',
  3,
  3,
  'medium',
  2.7614742996887696,
  'unknown',
  None),
 ('No', 3.0, 'medium', 3, 'involved', 3, 3, 'medium', 2.0, 'little', 1014.0),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 4, 'maximun', 3.0, 'medium', None),
 ('No',
  2.0,
  'little',
  2,
  'little involved',
  3,
  4,
  'maximun',
  3.0,
  'medium',
  1117.0),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 2, 'little', 3.0, 'medium', 1238.0),
 ('No', 3.0, 'medium', 3, 'involved', 2, 3, 'medium', 2.0, 'little', None),
 ('Yes',
  1.0,
  'nothing',
  1,
  'not involved',
  2,
  1,
  'nothing',
  3.0,
  'medium',
  1277.0),
 ('No',
  2.6566222845866387,
  'unknown',
  3,
  'involved',
  2,
  1,
  'nothing',
  2.0,
  'little',
  None),
 ('No', 2.0, 'little', 3, 'involved', 3, 2, 'little', 3.0, 'medium', 1541.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  1,
  'nothing',
  3.0,
  'medium',
  1666.0),
 ('No',
  2.0,
  'little',
  2,
  'little involved',
  4,
  3,
  'medium',
  2.766803720770763,
  'unknown',
  1696.0),
 ('No', 1.0, 'nothing', 3, 'involved', 2, 4, 'maximun', 3.0, 'medium', 1805.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  2,
  4,
  'maximun',
  3.0,
  'medium',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  2,
  'little',
  3.0,
  'medium',
  1932.0),
 ('No',
  2.780929777609628,
  'unknown',
  3,
  'involved',
  4,
  3,
  'medium',
  3.0,
  'medium',
  2016.0),
 ('No',
  2.0,
  'little',
  4,
  'very involved',
  1,
  3,
  'medium',
  3.0,
  'medium',
  20.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  1,
  3,
  'medium',
  2.0,
  'little',
  None),
 ('No', 3.0, 'medium', 3, 'involved', 4, 4, 'maximun', 1.0, 'nothing', 184.0),
 ('No',
  2.0,
  'little',
  3,
  'involved',
  2,
  3,
  'medium',
  2.7634057496763718,
  'unknown',
  206.0),
 ('No', 2.0, 'little', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', 228.0),
 ('No', 3.0, 'medium', 3, 'involved', 1, 3, 'medium', 3.0, 'medium', 239.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  3,
  'medium',
  2.0,
  'little',
  256.0),
 ('No',
  2.0,
  'little',
  2,
  'little involved',
  2,
  4,
  'maximun',
  1.0,
  'nothing',
  None),
 ('No',
  2.6543999684415143,
  'unknown',
  2,
  'little involved',
  1,
  2,
  'little',
  3.0,
  'medium',
  339.0),
 ('No', 3.0, 'medium', 3, 'involved', 2, 3, 'medium', 2.0, 'little', 406.0),
 ('No', 1.0, 'nothing', 3, 'involved', 1, 1, 'nothing', 3.0, 'medium', None),
 ('No', 3.0, 'medium', 3, 'involved', 1, 4, 'maximun', 3.0, 'medium', 429.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  1,
  'nothing',
  3.0,
  'medium',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  1,
  'nothing',
  3.0,
  'medium',
  444.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 1, 'nothing', 3.0, 'medium', 452.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  3,
  'medium',
  3.0,
  'medium',
  456.0),
 ('No', 3.0, 'medium', 3, 'involved', 4, 3, 'medium', 2.0, 'little', None),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  4,
  1,
  'nothing',
  3.0,
  'medium',
  481.0),
 ('No',
  2.0,
  'little',
  2,
  'little involved',
  3,
  2,
  'little',
  3.0,
  'medium',
  513.0),
 ('No', 1.0, 'nothing', 3, 'involved', 2, 4, 'maximun', 3.0, 'medium', 597.0),
 ('No', 2.0, 'little', 3, 'involved', 3, 3, 'medium', 3.0, 'medium', 600.0),
 ('No', 4.0, 'maximun', 3, 'involved', 1, 4, 'maximun', 2.0, 'little', None),
 ('No', 4.0, 'maximun', 3, 'involved', 1, 2, 'little', 3.0, 'medium', 630.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  3,
  'medium',
  3.0,
  'medium',
  638.0),
 ('No', 2.0, 'little', 3, 'involved', 4, 4, 'maximun', 2.0, 'little', 683.0),
 ('Yes', 4.0, 'maximun', 3, 'involved', 4, 3, 'medium', 2.0, 'little', 780.0),
 ('No', 3.0, 'medium', 3, 'involved', 3, 4, 'maximun', 4.0, 'maximun', 817.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', 901.0),
 ('No', 1.0, 'nothing', 3, 'involved', 2, 3, 'medium', 2.0, 'little', 944.0),
 ('No',
  2.716996754850474,
  'unknown',
  3,
  'involved',
  4,
  2,
  'little',
  3.0,
  'medium',
  984.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  1,
  'nothing',
  2.0,
  'little',
  1088.0),
 ('No', 1.0, 'nothing', 3, 'involved', 3, 4, 'maximun', 3.0, 'medium', 1124.0),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 1, 'nothing', 3.0, 'medium', None),
 ('Yes',
  2.793236787748048,
  'unknown',
  3,
  'involved',
  1,
  2,
  'little',
  2.0,
  'little',
  1167.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  1,
  3,
  'medium',
  3.0,
  'medium',
  1184.0),
 ('No', 4.0, 'maximun', 3, 'involved', 2, 1, 'nothing', 3.0, 'medium', None),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 1, 'nothing', 3.0, 'medium', None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  1,
  2,
  'little',
  3.0,
  'medium',
  1252.0),
 ('No', 2.0, 'little', 3, 'involved', 2, 3, 'medium', 3.0, 'medium', 1267.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  2,
  4,
  'maximun',
  3.0,
  'medium',
  1278.0),
 ('No',
  3.0,
  'medium',
  4,
  'very involved',
  1,
  4,
  'maximun',
  2.0,
  'little',
  1288.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  2,
  4,
  'maximun',
  4.0,
  'maximun',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  2,
  4,
  'maximun',
  3.0,
  'medium',
  1307.0),
 ('No',
  4.0,
  'maximun',
  1,
  'not involved',
  3,
  4,
  'maximun',
  3.0,
  'medium',
  1336.0),
 ('No', 3.0, 'medium', 3, 'involved', 2, 2, 'little', 3.0, 'medium', 1352.0),
 ('Yes',
  2.761710363941569,
  'unknown',
  2,
  'little involved',
  1,
  4,
  'maximun',
  2.0,
  'little',
  1360.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', None),
 ('No',
  2.0,
  'little',
  2,
  'little involved',
  1,
  1,
  'nothing',
  2.0,
  'little',
  1419.0),
 ('No',
  4.0,
  'maximun',
  1,
  'not involved',
  1,
  4,
  'maximun',
  3.0,
  'medium',
  1478.0),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', 1480.0),
 ('No',
  2.0,
  'little',
  4,
  'very involved',
  3,
  1,
  'nothing',
  2.0,
  'little',
  None),
 ('Yes',
  1.0,
  'nothing',
  2,
  'little involved',
  2,
  3,
  'medium',
  4.0,
  'maximun',
  1489.0),
 ('No', 2.0, 'little', 3, 'involved', 4, 1, 'nothing', 3.0, 'medium', 1520.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  4,
  'maximun',
  3.0,
  'medium',
  1535.0),
 ('No',
  2.0,
  'little',
  3,
  'involved',
  1,
  4,
  'maximun',
  2.75017190992444,
  'unknown',
  1586.0),
 ('No',
  2.0,
  'little',
  4,
  'very involved',
  3,
  4,
  'maximun',
  2.0,
  'little',
  1596.0),
 ('Yes',
  4.0,
  'maximun',
  3,
  'involved',
  4,
  1,
  'nothing',
  4.0,
  'maximun',
  1667.0),
 ('No',
  2.0,
  'little',
  2,
  'little involved',
  4,
  2,
  'little',
  3.0,
  'medium',
  1701.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 1, 'nothing', 3.0, 'medium', 1706.0),
 ('No', 2.0, 'little', 3, 'involved', 2, 4, 'maximun', 2.0, 'little', None),
 ('No',
  2.726717145035656,
  'unknown',
  2,
  'little involved',
  3,
  1,
  'nothing',
  3.0,
  'medium',
  None),
 ('No', 1.0, 'nothing', 3, 'involved', 3, 2, 'little', 3.0, 'medium', 1971.0),
 ('No',
  3.0,
  'medium',
  4,
  'very involved',
  2,
  1,
  'nothing',
  3.0,
  'medium',
  None),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  4,
  'maximun',
  3.0,
  'medium',
  1976.0),
 ('No',
  4.0,
  'maximun',
  3,
  'involved',
  3,
  1,
  'nothing',
  4.0,
  'maximun',
  1985.0),
 ('Yes',
  4.0,
  'maximun',
  3,
  'involved',
  3,
  4,
  'maximun',
  1.0,
  'nothing',
  2032.0),
 ('No',
  2.737189812092085,
  'unknown',
  2,
  'little involved',
  4,
  1,
  'nothing',
  2.0,
  'little',
  2056.0),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  4,
  3,
  'medium',
  3.0,
  'medium',
  None),
 ('No', 4.0, 'maximun', 3, 'involved', 3, 4, 'maximun', 3.0, 'medium', None),
 ('No',
  3.0,
  'medium',
  3,
  'involved',
  4,
  4,
  'maximun',
  2.7663893452973403,
  'unknown',
  57.0),
 ('No', 2.0, 'little', 3, 'involved', 1, 4, 'maximun', 2.0, 'little', None),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 2, 'little', 3.0, 'medium', 78.0),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  4,
  3,
  'medium',
  2.768483921037799,
  'unknown',
  104.0),
 ('Yes',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  4,
  'maximun',
  3.0,
  'medium',
  118.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  2,
  2,
  'little',
  2.0,
  'little',
  121.0),
 ('No', 2.0, 'little', 3, 'involved', 3, 1, 'nothing', 3.0, 'medium', 125.0),
 ('No', 3.0, 'medium', 3, 'involved', 2, 1, 'nothing', 3.0, 'medium', None),
 ('No', 2.0, 'little', 3, 'involved', 4, 4, 'maximun', 3.0, 'medium', 207.0),
 ('No', 1.0, 'nothing', 3, 'involved', 3, 1, 'nothing', 3.0, 'medium', 227.0),
 ('No', 4.0, 'maximun', 3, 'involved', 3, 2, 'little', 3.0, 'medium', 253.0),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  4,
  4,
  'maximun',
  3.0,
  'medium',
  264.0),
 ('Yes',
  4.0,
  'maximun',
  1,
  'not involved',
  4,
  3,
  'medium',
  2.0,
  'little',
  291.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  3,
  3,
  'medium',
  3.0,
  'medium',
  292.0),
 ('No', 2.0, 'little', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', 306.0),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 3, 'medium', 3.0, 'medium', None),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 1, 'nothing', 3.0, 'medium', 335.0),
 ('No', 2.0, 'little', 3, 'involved', 2, 3, 'medium', 3.0, 'medium', None),
 ('No',
  4.0,
  'maximun',
  2,
  'little involved',
  3,
  3,
  'medium',
  2.0,
  'little',
  420.0),
 ('No',
  1.0,
  'nothing',
  2,
  'little involved',
  2,
  3,
  'medium',
  3.0,
  'medium',
  421.0),
 ('No', 4.0, 'maximun', 3, 'involved', 4, 4, 'maximun', 3.0, 'medium', 441.0),
 ('No', 2.0, 'little', 3, 'involved', 3, 3, 'medium', 3.0, 'medium', 531.0),
 ('No', 1.0, 'nothing', 3, 'involved', 1, 4, 'maximun', 1.0, 'nothing', 549.0),
 ('No', 3.0, 'medium', 3, 'involved', 1, 3, 'medium', 3.0, 'medium', 567.0),
 ('No', 3.0, 'medium', 3, 'involved', 2, 4, 'maximun', 4.0, 'maximun', 581.0),
 ('Yes', 1.0, 'nothing', 3, 'involved', 1, 1, 'nothing', 3.0, 'medium', 702.0),
 ('No',
  4.0,
  'maximun',
  4,
  'very involved',
  3,
  3,
  'medium',
  3.0,
  'medium',
  716.0),
 ('No', 1.0, 'nothing', 3, 'involved', 4, 4, 'maximun', 3.0, 'medium', 772.0),
 ('No', 2.0, 'little', 3, 'involved', 2, 4, 'maximun', 2.0, 'little', 836.0),
 ('Yes', 3.0, 'medium', 3, 'involved', 4, 1, 'nothing', 4.0, 'maximun', 840.0),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  2,
  'little',
  3.0,
  'medium',
  844.0),
 ('No',
  1.0,
  'nothing',
  4,
  'very involved',
  1,
  1,
  'nothing',
  3.0,
  'medium',
  None),
 ('No',
  3.0,
  'medium',
  2,
  'little involved',
  4,
  3,
  'medium',
  3.0,
  'medium',
  867.0),
 ('No', 2.0, 'little', 3, 'involved', 2, 4, 'maximun', 3.0, 'medium', 889.0),
 ('No', 3.0, 'medium', 3, 'involved', 4, 1, 'nothing', 2.0, 'little', 924.0),
 ('No', 4.0, 'maximun', 3, 'involved', 3, 4, 'maximun', 2.0, 'little', None),
 ('No', 3.0, 'medium', 3, 'involved', 3, 3, 'medium', 3.0, 'medium', None),
 ('No',
  4.0,
  'maximun',
  3,
  'involved',
  4,
  2,
  'little',
  2.7572422920129656,
  'unknown',
  976.0),

In [26]:
cnx = mysql.connector.connect(user = "root",
                              password = "AlumnaAdalab",
                              host = "127.0.0.1",
                              database = "abc_proyecto")#Nuesta base de datos de mysql
#Nos permite enviar informacion atraves de la conexciosm
mycursor = cnx.cursor()


#Escribimos la query aqui
#¡¡¡El ORDEN IMPORTA!!! --> El primer dato debe ser el primer elemento de la lista de tuplas
sql_proyecto = "INSERT INTO abandono_satisfaccion (attrition, environmentsatisfaction, environmentsatisfaction_cat, jobinvolvement, jobinvolvement_cat, jobsatisfaction, relationshipsatisfaction, relationshipsatisfaction_cat, worklifebalance, worklifebalance_cat, employeenumber) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

                        #peliculas el nombre del archivo correspondiente
try:
    mycursor.executemany(sql_proyecto, lista_tuplas_abandono)
    cnx.commit()
    print(mycursor.rowcount,"registros insertados")
except Exception as e:
    print("Ha habido un error en la inserción:", e)

1571 registros insertados

In [27]:
df_detalles = definitivo[['age', 'gender', 'gender_cat', 'maritalstatus', 'distancefromhome', 'totalworkingyears', 'education', 'education_cat', 'educationfield', 'numcompaniesworked', 'employeenumber']]
df_detalles

,age,gender,gender_cat,maritalstatus,distancefromhome,totalworkingyears,education,education_cat,educationfield,numcompaniesworked,employeenumber
0,51,0,male,Unknown,6.0,11.262958,3,college,Unknown,7,162.0
1,52,0,male,Unknown,1.0,34.000000,4,Unknown,life sciences,0,259.0
2,42,0,male,married,4.0,22.000000,2,high school,technical degree,1,319.0
3,47,1,female,married,2.0,11.279048,4,Unknown,medical,3,NaN
4,46,1,female,divorced,3.0,11.259844,3,college,technical degree,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1607,31,1,female,Unknown,12.0,10.000000,3,college,medical,0,NaN
1608,32,1,female,married,3.0,8.000000,4,Unknown,medical,1,966.0
1610,45,0,male,Unknown,4.0,11.266156,2,high school,Unknown,1,972.0
1611,39,0,male,single,NaN,9.000000,5,university,Unknown,0,NaN
1613,46,0,male,Unknown,7.0,11.275501,2,high school,medical,6,NaN

In [28]:
df_detalles_none = df_detalles.replace([np.nan],[None] )

In [29]:
lista_tuplas_detalles = [tuple(x) for x in df_detalles_none.values]
lista_tuplas_detalles

[(51,
  0,
  'male',
  'Unknown',
  6.0,
  11.26295760540497,
  3,
  'college',
  'Unknown',
  7,
  162.0),
 (52,
  0,
  'male',
  'Unknown',
  1.0,
  34.0,
  4,
  'Unknown',
  'life sciences',
  0,
  259.0),
 (42,
  0,
  'male',
  'married',
  4.0,
  22.0,
  2,
  'high school',
  'technical degree',
  1,
  319.0),
 (47,
  1,
  'female',
  'married',
  2.0,
  11.279048410220383,
  4,
  'Unknown',
  'medical',
  3,
  None),
 (46,
  1,
  'female',
  'divorced',
  3.0,
  11.259844439676948,
  3,
  'college',
  'technical degree',
  2,
  None),
 (48,
  1,
  'female',
  'Unknown',
  22.0,
  11.26668030318142,
  3,
  'college',
  'medical',
  3,
  1900.0),
 (59,
  1,
  'female',
  'Unknown',
  25.0,
  28.0,
  3,
  'college',
  'life sciences',
  7,
  81.0),
 (42,
  0,
  'male',
  'married',
  1.0,
  20.0,
  1,
  'middle school',
  'Unknown',
  1,
  387.0),
 (41, 1, 'female', 'married', 2.0, 22.0, 5, 'university', 'Unknown', 7, None),
 (41, 0, 'male', 'Unknown', 9.0, 21.0, 3, 'college', 'Unknown', 2, 999.0),
 (41,
  1,
  'female',
  'Unknown',
  7.0,
  11.265063272921571,
  1,
  'middle school',
  'Unknown',
  1,
  1035.0),
 (56,
  0,
  'male',
  'married',
  23.0,
  33.0,
  3,
  'college',
  'life sciences',
  4,
  None),
 (38,
  1,
  'female',
  'married',
  10.0,
  11.28789315492708,
  3,
  'college',
  'medical',
  3,
  None),
 (41,
  1,
  'female',
  'married',
  12.0,
  11.261950107193549,
  3,
  'college',
  'Unknown',
  1,
  58.0),
 (55,
  0,
  'male',
  'single',
  14.0,
  11.268206662347517,
  4,
  'Unknown',
  'medical',
  8,
  None),
 (40,
  1,
  'female',
  'Unknown',
  2.0,
  11.277546159531584,
  4,
  'Unknown',
  'Unknown',
  0,
  558.0),
 (58, 0, 'male', 'single', 2.0, 40.0, 4, 'Unknown', 'Unknown', 7, 825.0),
 (46, 1, 'female', 'Unknown', 2.0, 28.0, 3, 'college', 'Unknown', 8, None),
 (35,
  0,
  'male',
  'married',
  None,
  11.261431246238878,
  5,
  'university',
  'life sciences',
  1,
  None),
 (40,
  1,
  'female',
  'Unknown',
  15.0,
  18.0,
  3,
  'college',
  'life sciences',
  1,
  None),
 (45,
  0,
  'male',
  'Unknown',
  1.0,
  25.0,
  1,
  'middle school',
  'Unknown',
  3,
  1712.0),
 (33,
  1,
  'female',
  'single',
  1.0,
  15.0,
  2,
  'high school',
  'life sciences',
  1,
  73.0),
 (36, 1, 'female', 'divorced', 8.0, 17.0, 3, 'college', 'Unknown', 1, None),
 (47,
  1,
  'female',
  'married',
  2.0,
  11.25370327937928,
  2,
  'high school',
  'other',
  1,
  820.0),
 (36,
  0,
  'male',
  'Unknown',
  None,
  18.0,
  2,
  'high school',
  'life sciences',
  1,
  None),
 (35,
  1,
  'female',
  'married',
  9.0,
  17.0,
  3,
  'college',
  'life sciences',
  1,
  None),
 (52,
  1,
  'female',
  'married',
  2.0,
  33.0,
  1,
  'middle school',
  'Unknown',
  1,
  None),
 (36,
  1,
  'female',
  'single',
  2.0,
  18.0,
  4,
  'Unknown',
  'life sciences',
  9,
  1294.0),
 (33,
  0,
  'male',
  'married',
  28.0,
  15.0,
  4,
  'Unknown',
  'life sciences',
  1,
  None),
 (34,
  0,
  'male',
  'Unknown',
  10.0,
  15.0,
  3,
  'college',
  'life sciences',
  1,
  1774.0),
 (41,
  1,
  'female',
  'divorced',
  None,
  11.27854902540433,
  1,
  'middle school',
  'Unknown',
  0,
  1815.0),
 (47, 0, 'male', 'Unknown', 25.0, 25.0, 3, 'college', 'medical', 2, 1993.0),
 (53, 1, 'female', 'Unknown', 5.0, 26.0, 3, 'college', 'Unknown', 4, 32.0),
 (35, 0, 'male', 'single', 1.0, 16.0, 4, 'Unknown', 'marketing', 0, 100.0),
 (34, 1, 'female', 'single', 6.0, 16.0, 4, 'Unknown', 'other', 1, None),
 (46,
  1,
  'female',
  'divorced',
  1.0,
  24.0,
  2,
  'high school',
  'Unknown',
  1,
  244.0),
 (43, 1, 'female', 'married', 16.0, 22.0, 3, 'college', 'Unknown', 5, 327.0),
 (36,
  0,
  'male',
  'married',
  6.0,
  16.0,
  3,
  'college',
  'life sciences',
  0,
  373.0),
 (60, 1, 'female', 'married', 28.0, 22.0, 3, 'college', 'Unknown', 4, None),
 (40, 0, 'male', 'married', 5.0, 20.0, 4, 'Unknown', 'Unknown', 5, 729.0),
 (32, 1, 'female', 'married', 4.0, 14.0, 3, 'college', 'Unknown', 1, 830.0),
 (41, 0, 'male', 'single', None, 20.0, 3, 'college', 'Unknown', 2, None),
 (53, 0, 'male', 'divorced', 2.0, 22.0, 2, 'high school', 'medical', 6, 981.0),
 (36, 1, 'female', 'single', 16.0, 18.0, 4, 'Unknown', 'Unknown', 1, 1042.0),
 (46,
  1,
  'female',
  'divorced',
  8.0,
  11.274982078456151,
  4,
  'Unknown',
  'life sciences',
  8,
  1080.0),
 (38, 0, 'male', 'married', 1.0, 16.0, 4, 'Unknown', 'Unknown', 0, 1995.0),
 (51, 1, 'female', 'single', 1.0, 23.0, 4, 'Unknown', 'Unknown', 3, 145.0),
 (43, 0, 'male', 'married', 26.0, 25.0, 2, 'high school', 'Unknown', 1, 158.0),
 (37,
  1,
  'female',
  'single',
  1.0,
  11.258378527906691,
  3,
  'college',
  'life sciences',
  1,
  391.0),
 (32,
  1,
  'female',
  'married',
  8.0,
  11.270282106166198,
  2,
  'high school',
  'technical degree',
  1,
  436.0),
 (38, 1, 'female', 'married', 1.0, 15.0, 3, 'college', 'Unknown', 1, None),
 (46,
  1,
  'female',
  'Unknown',
  3.0,
  23.0,
  3,
  'college',
  'life sciences',
  8,
  1527.0),
 (35, 0, 'male', 'married', 10.0, 15.0, 3, 'college', 'medical', 9, None),
 (43, 1, 'female', 'married', 6.0, 21.0, 3, 'college', 'medical', 7, 1866.0),
 (56,
  0,
  'male',
  'divorced',
  1.0,
  11.266155942291377,
  4,
  'Unknown',
  'life sciences',
  1,
  2026.0),
 (36,
  0,
  'male',
  'divorced',
  15.0,
  11.282270855584084,
  4,
  'Unknown',
  'marketing',
  1,
  None),
 (38, 1, 'female', 'Unknown', 6.0, 17.0, 3, 'college', 'medical', 7, 107.0),
 (49, 1, 'female', 'Unknown', None, 16.0, 4, 'Unknown', 'medical', 1, 170.0),
 (39,
  1,
  'female',
  'married',
  4.0,
  17.0,
  4,
  'Unknown',
  'life sciences',
  4,
  None),
 (40, 0, 'male', 'married', 4.0, 15.0, 4, 'Unknown', 'Unknown', 7, 215.0),
 (36, 0, 'male', 'single', 5.0, 16.0, 2, 'high school', 'Unknown', 8, 304.0),
 (37,
  1,
  'female',
  'married',
  25.0,
  15.0,
  5,
  'university',
  'Unknown',
  3,
  529.0),
 (35,
  0,
  'male',
  'Unknown',
  6.0,
  11.279072518697678,
  4,
  'Unknown',
  'Unknown',
  1,
  691.0),
 (33,
  0,
  'male',
  'divorced',
  6.0,
  15.0,
  3,
  'college',
  'life sciences',
  3,
  692.0),
 (50, 0, 'male', 'married', 24.0, 22.0, 3, 'college', 'Unknown', 3, 1005.0),
 (48, 0, 'male', 'single', 4.0, 27.0, 4, 'Unknown', 'Unknown', 7, 1024.0),
 (44,
  1,
  'female',
  'married',
  28.0,
  11.264085998408069,
  3,
  'college',
  'Unknown',
  3,
  1039.0),
 (44,
  0,
  'male',
  'single',
  29.0,
  11.253189918359986,
  4,
  'Unknown',
  'Unknown',
  1,
  1225.0),
 (40,
  1,
  'female',
  'Unknown',
  None,
  15.0,
  1,
  'middle school',
  'Unknown',
  5,
  1375.0),
 (34, 1, 'female', 'single', 2.0, 14.0, 4, 'Unknown', 'Unknown', 1, None),
 (35,
  1,
  'female',
  'Unknown',
  8.0,
  11.26353691375548,
  4,
  'Unknown',
  'Unknown',
  1,
  None),
 (50,
  1,
  'female',
  'Unknown',
  17.0,
  11.262529415544057,
  5,
  'university',
  'life sciences',
  5,
  None),
 (49,
  1,
  'female',
  'Unknown',
  6.0,
  11.257829443254105,
  1,
  'middle school',
  'life sciences',
  2,
  1661.0),
 (38,
  0,
  'male',
  'Unknown',
  1.0,
  19.0,
  3,
  'college',
  'life sciences',
  7,
  1668.0),
 (33, 0, 'male', 'Unknown', 21.0, 14.0, 3, 'college', 'Unknown', 1, 1698.0),
 (47,
  1,
  'female',
  'divorced',
  4.0,
  11.284291351942302,
  3,
  'college',
  'life sciences',
  8,
  None),
 (38, 1, 'female', 'divorced', 8.0, 20.0, 3, 'college', 'Unknown', 1, 1937.0),
 (37,
  1,
  'female',
  'Unknown',
  10.0,
  16.0,
  3,
  'college',
  'life sciences',
  1,
  2017.0),
 (30, 0, 'male', 'married', 2.0, 11.0, 3, 'college', 'Unknown', 1, 117.0),
 (58, 0, 'male', 'single', None, 38.0, 4, 'Unknown', 'Unknown', 0, 131.0),
 (34, 1, 'female', 'single', 5.0, 14.0, 3, 'college', 'Unknown', 2, 153.0),
 (58, 1, 'female', 'married', 23.0, 40.0, 4, 'Unknown', 'medical', 1, None),
 (38,
  0,
  'male',
  'divorced',
  3.0,
  11.27595385303428,
  3,
  'college',
  'life sciences',
  0,
  307.0),
 (29,
  1,
  'female',
  'married',
  1.0,
  11.0,
  1,
  'middle school',
  'Unknown',
  1,
  None),
 (55, 0, 'male', 'single', 1.0, 37.0, 3, 'college', 'medical', 0, 374.0),
 (41,
  0,
  'male',
  'Unknown',
  None,
  11.28224613182154,
  4,
  'Unknown',
  'Unknown',
  1,
  None),
 (39, 0, 'male', 'Unknown', 1.0, 19.0, 3, 'college', 'Unknown', 0, None),
 (38,
  0,
  'male',
  'Unknown',
  15.0,
  11.284291351942302,
  2,
  'high school',
  'life sciences',
  0,
  None),
 (43,
  0,
  'male',
  'Unknown',
  12.0,
  11.267114293008904,
  3,
  'college',
  'Unknown',
  1,
  None),
 (31,
  1,
  'female',
  'married',
  None,
  13.0,
  2,
  'high school',
  'Unknown',
  1,
  524.0),
 (50,
  0,
  'male',
  'married',
  None,
  28.0,
  4,
  'Unknown',
  'life sciences',
  0,
  569.0),
 (35,
  0,
  'male',
  'married',
  25.0,
  11.277057522274834,
  3,
  'college',
  'technical degree',
  3,
  899.0),
 (47, 0, 'male', 'Unknown', 16.0, 20.0, 4, 'Unknown', 'Unknown', 1, None),
 (35,
  1,
  'female',
  'divorced',
  25.0,
  11.266155942291377,
  4,
  'Unknown',
  'Unknown',
  1,
  1014.0),
 (40, 0, 'male', 'married', 20.0, 14.0, 4, 'Unknown', 'Unknown', 4, None),
 (45,
  1,
  'female',
  'married',
  9.0,
  15.0,
  4,
  'Unknown',
  'life sciences',
  1,
  1117.0),
 (33, 0, 'male', 'married', 9.0, 15.0, 3, 'college', 'medical', 0, 1238.0),
 (36, 0, 'male', 'married', 3.0, 12.0, 3, 'college', 'Unknown', 1, None),
 (45,
  1,
  'female',
  'Unknown',
  None,
  26.0,
  3,
  'college',
  'marketing',
  2,
  1277.0),
 (51,
  0,
  'male',
  'Unknown',
  None,
  11.279635948968467,
  3,
  'college',
  'Unknown',
  4,
  None),
 (34,
  0,
  'male',
  'Unknown',
  7.0,
  12.0,
  2,
  'high school',
  'technical degree',
  0,
  1541.0),
 (43,
  0,
  'male',
  'Unknown',
  15.0,
  11.270282106166198,
  2,
  'high school',
  'Unknown',
  1,
  1666.0),
 (34,
  0,
  'male',
  'Unknown',
  5.0,
  11.266106760320348,
  2,
  'high school',
  'medical',
  1,
  1696.0),
 (38, 0, 'male', 'divorced', 2.0, 13.0, 3, 'college', 'Unknown', 5, 1805.0),
 (48, 0, 'male', 'Unknown', 10.0, 29.0, 3, 'college', 'Unknown', 4, None),
 (34, 0, 'male', 'married', 22.0, 16.0, 4, 'Unknown', 'other', 1, 1932.0),
 (32, 1, 'female', 'Unknown', None, 14.0, 4, 'Unknown', 'Unknown', 1, 2016.0),
 (29,
  1,
  'female',
  'divorced',
  21.0,
  10.0,
  4,
  'Unknown',
  'life sciences',
  1,
  20.0),
 (46, 0, 'male', 'married', 1.0, 21.0, 3, 'college', 'medical', 2, None),
 (30,
  0,
  'male',
  'married',
  9.0,
  11.261510917461884,
  3,
  'college',
  'Unknown',
  0,
  184.0),
 (45,
  0,
  'male',
  'Unknown',
  9.0,
  20.0,
  3,
  'college',
  'life sciences',
  8,
  206.0),
 (30,
  1,
  'female',
  'Unknown',
  5.0,
  11.257799219556183,
  3,
  'college',
  'Unknown',
  2,
  228.0),
 (30, 0, 'male', 'Unknown', 9.0, 12.0, 3, 'college', 'Unknown', 1, 239.0),
 (34,
  0,
  'male',
  'married',
  None,
  10.0,
  1,
  'middle school',
  'Unknown',
  1,
  256.0),
 (51, 0, 'male', 'married', 8.0, 16.0, 4, 'Unknown', 'life sciences', 5, None),
 (34,
  0,
  'male',
  'Unknown',
  None,
  13.0,
  4,
  'Unknown',
  'life sciences',
  6,
  339.0),
 (35, 0, 'male', 'married', 16.0, 12.0, 3, 'college', 'Unknown', 0, 406.0),
 (45, 0, 'male', 'Unknown', 7.0, 24.0, 3, 'college', 'life sciences', 1, None),
 (39,
  0,
  'male',
  'married',
  10.0,
  21.0,
  1,
  'middle school',
  'Unknown',
  1,
  429.0),
 (31, 1, 'female', 'married', 7.0, 10.0, 2, 'high school', 'Unknown', 1, None),
 (39,
  0,
  'male',
  'married',
  7.0,
  11.26457463566482,
  2,
  'high school',
  'Unknown',
  1,
  444.0),
 (45, 0, 'male', 'Unknown', 8.0, 12.0, 4, 'Unknown', 'Unknown', 9, 452.0),
 (30, 1, 'female', 'Unknown', 5.0, 10.0, 3, 'college', 'marketing', 1, 456.0),
 (31, 1, 'female', 'Unknown', 7.0, 11.0, 4, 'Unknown', 'medical', 1, None),
 (36, 0, 'male', 'married', 3.0, 16.0, 4, 'Unknown', 'medical', 4, 481.0),
 (36, 0, 'male', 'married', 2.0, 10.0, 2, 'high school', 'Unknown', 1, 513.0),
 (55, 1, 'female', 'single', 18.0, 37.0, 5, 'university', 'Unknown', 3, 597.0),
 (35, 0, 'male', 'Unknown', 1.0, 15.0, 3, 'college', 'Unknown', 9, 600.0),
 (42, 0, 'male', 'married', 24.0, 10.0, 3, 'college', 'medical', 1, None),
 (52, 0, 'male', 'divorced', 6.0, 18.0, 2, 'high school', 'Unknown', 3, 630.0),
 (49,
  0,
  'male',
  'Unknown',
  18.0,
  11.26668030318142,
  4,
  'Unknown',
  'life sciences',
  1,
  638.0),
 (34,
  0,
  'male',
  'married',
  1.0,
  11.258342804273395,
  5,
  'university',
  'Unknown',
  1,
  683.0),
 (33, 0, 'male', 'single', 1.0, 10.0, 4, 'Unknown', 'other', 1, 780.0),
 (33,
  0,
  'male',
  'married',
  7.0,
  11.261955607128924,
  3,
  'college',
  'medical',
  0,
  817.0),
 (53, 1, 'female', 'Unknown', 23.0, 33.0, 4, 'Unknown', 'Unknown', 6, 901.0),
 (49, 1, 'female', 'married', 8.0, 29.0, 2, 'high school', 'other', 4, 944.0),
 (35,
  0,
  'male',
  'Unknown',
  None,
  11.27075390410716,
  4,
  'Unknown',
  'Unknown',
  6,
  984.0),
 (38,
  1,
  'female',
  'married',
  17.0,
  20.0,
  1,
  'middle school',
  'life sciences',
  0,
  1088.0),
 (46,
  0,
  'male',
  'married',
  3.0,
  11.271509930478269,
  1,
  'middle school',
  'marketing',
  3,
  1124.0),
 (36, 0, 'male', 'single', 18.0, 18.0, 4, 'Unknown', 'Unknown', 2, None),
 (42,
  0,
  'male',
  'single',
  None,
  11.25940450073179,
  3,
  'college',
  'life sciences',
  0,
  1167.0),
 (34, 0, 'male', 'single', 1.0, 14.0, 3, 'college', 'Unknown', 0, 1184.0),
 (30, 0, 'male', 'Unknown', 1.0, 12.0, 3, 'college', 'medical', 0, None),
 (54, 0, 'male', 'married', 3.0, 36.0, 3, 'college', 'life sciences', 3, None),
 (31, 1, 'female', 'single', 24.0, 10.0, 3, 'college', 'medical', 1, 1252.0),
 (44, 0, 'male', 'married', 5.0, 26.0, 3, 'college', 'Unknown', 7, 1267.0),
 (55,
  0,
  'male',
  'divorced',
  8.0,
  11.255784223133338,
  1,
  'middle school',
  'Unknown',
  1,
  1278.0),
 (44,
  0,
  'male',
  'divorced',
  4.0,
  11.284316075704847,
  2,
  'high school',
  'life sciences',
  1,
  1288.0),
 (34,
  0,
  'male',
  'Unknown',
  11.0,
  14.0,
  3,
  'college',
  'life sciences',
  4,
  None),
 (39,
  1,
  'female',
  'divorced',
  13.0,
  11.285329073851644,
  4,
  'Unknown',
  'Unknown',
  6,
  1307.0),
 (55,
  1,
  'female',
  'Unknown',
  2.0,
  23.0,
  2,
  'high school',
  'medical',
  4,
  1336.0),
 (51,
  0,
  'male',
  'Unknown',
  5.0,
  11.28014046430494,
  3,
  'college',
  'life sciences',
  1,
  1352.0),
 (58,
  1,
  'female',
  'married',
  None,
  11.264073296478715,
  4,
  'Unknown',
  'medical',
  7,
  1360.0),
 (48, 0, 'male', 'single', 4.0, 11.0, 3, 'college', 'life sciences', 1, None),
 (29,
  0,
  'male',
  'single',
  17.0,
  11.263012552865431,
  3,
  'college',
  'Unknown',
  1,
  1419.0),
 (34, 0, 'male', 'single', 3.0, 15.0, 3, 'college', 'other', 3, 1478.0),
 (42,
  1,
  'female',
  'Unknown',
  9.0,
  12.0,
  2,
  'high school',
  'Unknown',
  1,
  1480.0),
 (57,
  0,
  'male',
  'married',
  1.0,
  13.0,
  2,
  'high school',
  'life sciences',
  0,
  None),
 (34, 1, 'female', 'single', 24.0, 16.0, 4, 'Unknown', 'Unknown', 0, 1489.0),
 (54, 1, 'female', 'Unknown', 11.0, 26.0, 4, 'Unknown', 'medical', 3, 1520.0),
 (34,
  0,
  'male',
  'Unknown',
  1.0,
  11.269793468909445,
  3,
  'college',
  'Unknown',
  1,
  1535.0),
 (29,
  0,
  'male',
  'single',
  3.0,
  11.281673000161408,
  1,
  'middle school',
  'medical',
  1,
  1586.0),
 (35,
  0,
  'male',
  'Unknown',
  28.0,
  11.26041824809208,
  3,
  'college',
  'life sciences',
  1,
  1596.0),
 (35, 0, 'male', 'Unknown', 12.0, 13.0, 4, 'Unknown', 'other', 3, 1667.0),
 (34,
  1,
  'female',
  'married',
  19.0,
  10.0,
  3,
  'college',
  'life sciences',
  1,
  1701.0),
 (43, 0, 'male', 'Unknown', 2.0, 10.0, 3, 'college', 'Unknown', 1, 1706.0),
 (58, 0, 'male', 'divorced', 2.0, 37.0, 3, 'college', 'medical', 4, None),
 (36, 1, 'female', 'married', None, 10.0, 4, 'Unknown', 'Unknown', 1, None),
 (43,
  0,
  'male',
  'married',
  11.0,
  10.0,
  3,
  'college',
  'life sciences',
  1,
  1971.0),
 (55,
  0,
  'male',
  'married',
  26.0,
  35.0,
  4,
  'Unknown',
  'human resources',
  4,
  None),
 (42, 0, 'male', 'single', 23.0, 20.0, 2, 'high school', 'Unknown', 1, 1976.0),
 (40,
  1,
  'female',
  'married',
  11.0,
  10.0,
  3,
  'college',
  'technical degree',
  1,
  1985.0),
 (56,
  0,
  'male',
  'married',
  7.0,
  14.0,
  2,
  'high school',
  'technical degree',
  8,
  2032.0),
 (39,
  1,
  'female',
  'Unknown',
  None,
  11.267704582059658,
  1,
  'middle school',
  'marketing',
  0,
  2056.0),
 (53,
  1,
  'female',
  'married',
  2.0,
  11.276966851181076,
  4,
  'Unknown',
  'life sciences',
  2,
  None),
 (27, 0, 'male', 'single', 8.0, 9.0, 3, 'college', 'Unknown', 1, None),
 (30, 1, 'female', 'Unknown', 1.0, 12.0, 2, 'high school', 'Unknown', 1, 57.0),
 (35,
  0,
  'male',
  'married',
  18.0,
  9.0,
  5,
  'university',
  'life sciences',
  1,
  None),
 (32, 0, 'male', 'married', 1.0, 9.0, 3, 'college', 'medical', 1, 78.0),
 (30,
  0,
  'male',
  'married',
  1.0,
  11.265129444265972,
  1,
  'middle school',
  'life sciences',
  1,
  104.0),
 (46, 0, 'male', 'Unknown', 9.0, 9.0, 2, 'high school', 'medical', 1, 118.0),
 (30,
  1,
  'female',
  'Unknown',
  4.0,
  11.0,
  2,
  'high school',
  'Unknown',
  1,
  121.0),
 (32, 0, 'male', 'single', 6.0, 12.0, 4, 'Unknown', 'Unknown', 1, 125.0),
 (35,
  0,
  'male',
  'married',
  None,
  11.285329073851644,
  5,
  'university',
  'marketing',
  1,
  None),
 (32, 1, 'female', 'single', 8.0, 9.0, 3, 'college', 'marketing', 1, 207.0),
 (41,
  0,
  'male',
  'divorced',
  None,
  11.265551910178324,
  3,
  'college',
  'life sciences',
  4,
  227.0),
 (40,
  1,
  'female',
  'Unknown',
  4.0,
  21.0,
  1,
  'middle school',
  'medical',
  1,
  253.0),
 (45, 0, 'male', 'married', 2.0, 22.0, 2, 'high school', 'Unknown', 9, 264.0),
 (32, 0, 'male', 'married', 4.0, 14.0, 4, 'Unknown', 'Unknown', 1, 291.0),
 (30,
  0,
  'male',
  'Unknown',
  1.0,
  11.282215908123622,
  1,
  'middle school',
  'life sciences',
  1,
  292.0),
 (37,
  0,
  'male',
  'Unknown',
  11.0,
  11.260912385284207,
  3,
  'college',
  'Unknown',
  1,
  306.0),
 (37, 0, 'male', 'divorced', 4.0, 13.0, 4, 'Unknown', 'Unknown', 4, None),
 (40,
  0,
  'male',
  'Unknown',
  24.0,
  11.268665075906348,
  2,
  'high school',
  'technical degree',
  1,
  335.0),
 (36, 1, 'female', 'married', 24.0, 11.0, 4, 'Unknown', 'Unknown', 7, None),
 (32,
  0,
  'male',
  'married',
  7.0,
  13.0,
  3,
  'college',
  'life sciences',
  1,
  420.0),
 (38,
  1,
  'female',
  'Unknown',
  25.0,
  11.27852343404509,
  2,
  'high school',
  'life sciences',
  3,
  421.0),
 (30,
  1,
  'female',
  'married',
  28.0,
  11.0,
  2,
  'high school',
  'Unknown',
  1,
  441.0),
 (39,
  0,
  'male',
  'Unknown',
  1.0,
  21.0,
  1,
  'middle school',
  'Unknown',
  1,
  531.0),
 (60,
  1,
  'female',
  'Unknown',
  7.0,
  33.0,
  3,
  'college',
  'life sciences',
  5,
  549.0),
 (30, 1, 'female', 'Unknown', 22.0, 10.0, 4, 'Unknown', 'other', 0, 567.0),
 (31,
  0,
  'male',
  'divorced',
  9.0,
  11.270483320280702,
  1,
  'middle school',
  'Unknown',
  1,
  581.0),
 (33,
  0,
  'male',
  'single',
  3.0,
  11.272815963543712,
  3,
  'college',
  'life sciences',
  1,
  702.0),
 (50,
  0,
  'male',
  'married',
  28.0,
  20.0,
  1,
  'middle school',
  'medical',
  1,
  716.0),
 (32,
  0,
  'male',
  'Unknown',
  24.0,
  10.0,
  4,
  'Unknown',
  'life sciences',
  1,
  772.0),
 (42, 0, 'male', 'Unknown', 29.0, 10.0, 3, 'college', 'Unknown', 1, 836.0),
 (49,
  1,
  'female',
  'married',
  11.0,
  11.2588424414009,
  3,
  'college',
  'marketing',
  1,
  840.0),
 (27,
  0,
  'male',
  'divorced',
  5.0,
  11.258348304208774,
  1,
  'middle school',
  'Unknown',
  1,
  844.0),
 (33, 0, 'male', 'divorced', 1.0, 9.0, 3, 'college', 'medical', 1, None),
 (52, 1, 'female', 'married', None, 31.0, 4, 'Unknown', 'Unknown', 3, 867.0),
 (32,
  0,
  'male',
  'Unknown',
  5.0,
  10.0,
  2,
  'high school',
  'life sciences',
  1,
  889.0),
 (36,
  0,
  'male',
  'Unknown',
  14.0,
  11.271863412792753,
  1,

In [30]:
cnx = mysql.connector.connect(user = "root",
                              password = "AlumnaAdalab",
                              host = "127.0.0.1",
                              database = "abc_proyecto")#Nuesta base de datos de mysql
#Nos permite enviar informacion atraves de la conexciosm
mycursor = cnx.cursor()


#Escribimos la query aqui
#¡¡¡El ORDEN IMPORTA!!! --> El primer dato debe ser el primer elemento de la lista de tuplas
#sql_proyecto1 = "INSERT INTO salario (dailyrate, monthlyrate, percentsalaryhike, hourlyrate, employeenumber) VALUES (%s, %s, %s, %s,%s)" 
sql_proyecto = "INSERT INTO detalles_personales (age, gender, gender_cat, maritalstatus, distancefromhome, totalworkingyears, education, education_cat, educationfield, numcompaniesworked, employeenumber) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

try:
    mycursor.executemany(sql_proyecto, lista_tuplas_detalles)
    cnx.commit()
    print(mycursor.rowcount,"registros insertados")
except Exception as e:
    print("Ha habido un error en la inserción:", e)

1571 registros insertados

In [31]:
df_condiciones = definitivo[['businesstravel', 'department', 'joblevel', 'jobrole', 'overtime', 'stockoptionlevel', 'trainingtimeslastyear', 'yearsatcompany', 'yearssincelastpromotion', 'yearswithcurrmanager', 'remotework', 'employeenumber']]
df_condiciones

,businesstravel,department,joblevel,jobrole,overtime,stockoptionlevel,trainingtimeslastyear,yearsatcompany,yearssincelastpromotion,yearswithcurrmanager,remotework,employeenumber
0,Unknown,Unknown,5,research director,No,0,5,20,15,15,Yes,162.0
1,Unknown,Unknown,5,manager,Unknown,1,5,33,11,9,Yes,259.0
2,travel_rarely,Research & Development,5,manager,No,0,3,22,11,15,Yes,319.0
3,travel_rarely,Unknown,4,research director,Unknown,2,2,20,5,6,No,NaN
4,Unknown,Unknown,4,sales executive,No,1,5,19,2,8,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1607,Unknown,Unknown,2,healthcare representative,Unknown,2,2,9,8,5,Yes,NaN
1608,Unknown,Unknown,2,manufacturing director,Unknown,1,2,8,6,3,Yes,966.0
1610,non-travel,Unknown,2,laboratory technician,Unknown,0,5,9,0,8,Yes,972.0
1611,travel_rarely,Unknown,3,sales executive,No,0,3,8,0,7,Yes,NaN
1613,Unknown,Unknown,3,manufacturing director,Unknown,1,3,8,0,7,No,NaN

In [32]:
df_condiciones_none = df_condiciones.replace([np.nan],[None] )

In [33]:
lista_tuplas_condiciones = [tuple(x) for x in df_condiciones_none.values]
lista_tuplas_condiciones

[('Unknown',
  'Unknown',
  5,
  ' research director ',
  'No',
  0,
  5,
  20,
  15,
  15,
  'Yes',
  162.0),
 ('Unknown',
  'Unknown',
  5,
  ' manager ',
  'Unknown',
  1,
  5,
  33,
  11,
  9,
  'Yes',
  259.0),
 ('travel_rarely',
  ' Research & Development ',
  5,
  ' manager ',
  'No',
  0,
  3,
  22,
  11,
  15,
  'Yes',
  319.0),
 ('travel_rarely',
  'Unknown',
  4,
  ' research director ',
  'Unknown',
  2,
  2,
  20,
  5,
  6,
  'No',
  None),
 ('Unknown',
  'Unknown',
  4,
  ' sales executive ',
  'No',
  1,
  5,
  19,
  2,
  8,
  'No',
  None),
 ('Unknown',
  ' Research & Development ',
  4,
  ' manager ',
  'No',
  1,
  3,
  22,
  4,
  7,
  'Yes',
  1900.0),
 ('Unknown',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  0,
  3,
  21,
  7,
  9,
  'Yes',
  81.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' sales executive ',
  'No',
  0,
  3,
  20,
  11,
  6,
  'No',
  387.0),
 ('Unknown', 'Unknown', 4, ' manager ', 'No', 1, 2, 18, 11, 8, 'Yes', None),
 ('travel_frequently',
  'Unknown',
  5,
  ' research director ',
  'No',
  1,
  2,
  18,
  0,
  11,
  'No',
  999.0),
 ('non-travel',
  'Unknown',
  5,
  ' research director ',
  'No',
  2,
  3,
  21,
  5,
  10,
  'No',
  1035.0),
 ('travel_rarely',
  'Unknown',
  4,
  ' manufacturing director ',
  'Yes',
  1,
  0,
  19,
  15,
  9,
  'No',
  None),
 ('Unknown',
  'Unknown',
  3,
  ' research director ',
  'No',
  1,
  3,
  18,
  1,
  11,
  'Yes',
  None),
 ('travel_rarely',
  'Unknown',
  5,
  ' research director ',
  'No',
  0,
  0,
  22,
  15,
  8,
  'No',
  58.0),
 ('Unknown',
  'Unknown',
  5,
  ' research director ',
  'No',
  0,
  3,
  24,
  2,
  15,
  'Yes',
  None),
 ('travel_rarely',
  'Unknown',
  5,
  ' manager ',
  'No',
  0,
  2,
  20,
  1,
  12,
  'No',
  558.0),
 ('travel_rarely',
  'Unknown',
  5,
  ' research director ',
  'Yes',
  0,
  2,
  31,
  13,
  8,
  'No',
  825.0),
 ('travel_rarely',
  'Unknown',
  4,
  ' manager ',
  'Unknown',
  0,
  2,
  26,
  15,
  9,
  'No',
  None),
 ('Unknown',
  'Unknown',
  2,
  ' research scientist ',
  'Unknown',
  0,
  2,
  16,
  1,
  10,
  'No',
  None),
 ('travel_rarely',
  'Unknown',
  3,
  ' manufacturing director ',
  'Unknown',
  2,
  2,
  18,
  14,
  12,
  'Yes',
  None),
 ('non-travel',
  ' Research & Development ',
  3,
  ' healthcare representative ',
  'Unknown',
  1,
  3,
  23,
  14,
  4,
  'No',
  1712.0),
 ('Unknown',
  'Unknown',
  3,
  ' research director ',
  'Yes',
  0,
  1,
  15,
  8,
  12,
  'Yes',
  73.0),
 ('Unknown',
  'Unknown',
  3,
  ' healthcare representative ',
  'Unknown',
  3,
  2,
  17,
  12,
  8,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  4,
  ' manager ',
  'Unknown',
  1,
  3,
  26,
  3,
  0,
  'No',
  820.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' sales executive ',
  'Unknown',
  1,
  1,
  18,
  4,
  11,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  3,
  ' manufacturing director ',
  'Yes',
  1,
  2,
  17,
  5,
  15,
  'No',
  None),
 ('Unknown', 'Unknown', 5, ' manager ', 'No', 1, 3, 32, 6, 9, 'Yes', None),
 ('Unknown',
  'Unknown',
  2,
  ' manufacturing director ',
  'Yes',
  0,
  2,
  16,
  5,
  12,
  'No',
  1294.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' laboratory technician ',
  'Unknown',
  1,
  3,
  15,
  5,
  7,
  'Yes',
  None),
 ('non-travel',
  ' Sales ',
  2,
  ' sales executive ',
  'Yes',
  1,
  3,
  15,
  0,
  7,
  'Yes',
  1774.0),
 ('Unknown',
  ' Sales ',
  3,
  ' sales executive ',
  'Unknown',
  1,
  3,
  22,
  13,
  5,
  'Yes',
  1815.0),
 ('Unknown',
  ' Research & Development ',
  3,
  ' healthcare representative ',
  'Unknown',
  0,
  3,
  17,
  12,
  11,
  'Yes',
  1993.0),
 ('travel_rarely',
  'Unknown',
  5,
  ' manager ',
  'Unknown',
  1,
  3,
  14,
  4,
  8,
  'Yes',
  32.0),
 ('Unknown',
  'Unknown',
  2,
  ' sales executive ',
  'No',
  0,
  2,
  15,
  2,
  8,
  'No',
  100.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' research scientist ',
  'Unknown',
  0,
  3,
  16,
  2,
  10,
  'Yes',
  None),
 ('travel_rarely',
  'Unknown',
  3,
  ' sales executive ',
  'No',
  3,
  2,
  24,
  15,
  7,
  'Yes',
  244.0),
 ('Unknown',
  'Unknown',
  4,
  ' manager ',
  'Unknown',
  1,
  3,
  17,
  1,
  9,
  'Yes',
  327.0),
 ('Unknown',
  ' Research & Development ',
  1,
  ' laboratory technician ',
  'Unknown',
  1,
  4,
  15,
  10,
  11,
  'Yes',
  373.0),
 ('travel_frequently',
  'Unknown',
  3,
  ' sales executive ',
  'No',
  0,
  5,
  18,
  13,
  11,
  'Yes',
  None),
 ('travel_frequently',
  'Unknown',
  3,
  ' sales executive ',
  'Yes',
  1,
  2,
  18,
  1,
  12,
  'No',
  729.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' manufacturing director ',
  'No',
  1,
  3,
  14,
  6,
  8,
  'No',
  830.0),
 ('travel_rarely',
  'Unknown',
  1,
  ' laboratory technician ',
  'Yes',
  0,
  3,
  18,
  2,
  17,
  'Yes',
  None),
 ('Unknown', 'Unknown', 4, ' manager ', 'No', 1, 3, 17, 15, 2, 'No', 981.0),
 ('travel_rarely',
  'Unknown',
  1,
  ' laboratory technician ',
  'Unknown',
  0,
  1,
  17,
  15,
  14,
  'Yes',
  1042.0),
 ('Unknown',
  'Unknown',
  2,
  ' research scientist ',
  'Yes',
  3,
  2,
  16,
  1,
  7,
  'No',
  1080.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' sales executive ',
  'No',
  2,
  3,
  15,
  5,
  8,
  'Yes',
  1995.0),
 ('Unknown',
  'Unknown',
  3,
  ' healthcare representative ',
  'Unknown',
  0,
  1,
  13,
  12,
  8,
  'Yes',
  145.0),
 ('Unknown', 'Unknown', 4, ' manager ', 'Yes', 2, 3, 25, 4, 12, 'Yes', 158.0),
 ('Unknown',
  'Unknown',
  1,
  ' research scientist ',
  'No',
  0,
  3,
  17,
  5,
  7,
  'Yes',
  391.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' sales executive ',
  'Yes',
  0,
  2,
  13,
  11,
  9,
  'Yes',
  436.0),
 ('Unknown',
  'Unknown',
  3,
  ' research director ',
  'Unknown',
  1,
  3,
  15,
  5,
  11,
  'No',
  None),
 ('Unknown', 'Unknown', 4, ' manager ', 'No', 1, 2, 13, 5, 1, 'Yes', 1527.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  0,
  3,
  13,
  6,
  0,
  'No',
  None),
 ('Unknown', 'Unknown', 5, ' manager ', 'No', 0, 2, 16, 6, 14, 'Yes', 1866.0),
 ('non-travel',
  'Unknown',
  2,
  ' healthcare representative ',
  'No',
  1,
  2,
  13,
  1,
  9,
  'Yes',
  2026.0),
 ('non-travel',
  'Unknown',
  2,
  ' sales executive ',
  'No',
  1,
  4,
  15,
  11,
  11,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  2,
  ' research scientist ',
  'Unknown',
  3,
  3,
  13,
  1,
  9,
  'Yes',
  107.0),
 ('Unknown',
  'Unknown',
  2,
  ' manufacturing director ',
  'No',
  0,
  2,
  15,
  5,
  11,
  'No',
  170.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' sales executive ',
  'Unknown',
  1,
  1,
  15,
  5,
  9,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  3,
  ' sales executive ',
  'No',
  1,
  2,
  12,
  2,
  11,
  'Yes',
  215.0),
 ('Unknown',
  'Unknown',
  2,
  ' laboratory technician ',
  'No',
  0,
  3,
  13,
  3,
  7,
  'Yes',
  304.0),
 ('Unknown',
  'Unknown',
  2,
  ' research scientist ',
  'Yes',
  2,
  2,
  13,
  10,
  7,
  'No',
  529.0),
 ('Unknown',
  'Unknown',
  2,
  ' research scientist ',
  'Unknown',
  0,
  3,
  17,
  11,
  8,
  'Yes',
  691.0),
 ('travel_frequently',
  'Unknown',
  2,
  ' healthcare representative ',
  'No',
  1,
  2,
  13,
  4,
  7,
  'No',
  692.0),
 ('travel_rarely',
  ' Research & Development ',
  4,
  ' manufacturing director ',
  'Yes',
  1,
  2,
  12,
  1,
  5,
  'No',
  1005.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' healthcare representative ',
  'Unknown',
  0,
  3,
  15,
  4,
  8,
  'Yes',
  1024.0),
 ('travel_rarely',
  ' Sales ',
  4,
  ' sales executive ',
  'Unknown',
  1,
  2,
  12,
  11,
  11,
  'Yes',
  1039.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' research scientist ',
  'Unknown',
  0,
  3,
  20,
  13,
  17,
  'Yes',
  1225.0),
 ('Unknown',
  'Unknown',
  2,
  ' healthcare representative ',
  'No',
  3,
  0,
  12,
  11,
  8,
  'Yes',
  1375.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' healthcare representative ',
  'Unknown',
  0,
  2,
  14,
  4,
  11,
  'Yes',
  None),
 ('non-travel',
  ' Research & Development ',
  2,
  ' healthcare representative ',
  'Unknown',
  1,
  5,
  14,
  2,
  9,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  3,
  ' research director ',
  'No',
  3,
  3,
  14,
  1,
  11,
  'No',
  None),
 ('Unknown',
  'Unknown',
  4,
  ' healthcare representative ',
  'Unknown',
  1,
  3,
  15,
  2,
  12,
  'Yes',
  1661.0),
 ('travel_frequently',
  'Unknown',
  2,
  ' research scientist ',
  'No',
  2,
  4,
  13,
  2,
  9,
  'Yes',
  1668.0),
 ('Unknown',
  'Unknown',
  1,
  ' laboratory technician ',
  'No',
  3,
  6,
  14,
  2,
  13,
  'Yes',
  1698.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' manufacturing director ',
  'Yes',
  1,
  4,
  22,
  14,
  10,
  'Yes',
  None),
 ('Unknown',
  ' Research & Development ',
  2,
  ' research scientist ',
  'Unknown',
  1,
  3,
  20,
  0,
  7,
  'No',
  1937.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' research director ',
  'Yes',
  1,
  2,
  16,
  6,
  8,
  'Yes',
  2017.0),
 ('Unknown',
  'Unknown',
  2,
  ' healthcare representative ',
  'No',
  3,
  3,
  11,
  10,
  8,
  'Yes',
  117.0),
 ('travel_rarely',
  'Unknown',
  4,
  ' sales executive ',
  'Unknown',
  0,
  1,
  37,
  1,
  8,
  'Yes',
  131.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' manager ',
  'Unknown',
  0,
  6,
  11,
  5,
  8,
  'No',
  153.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' healthcare representative ',
  'Unknown',
  1,
  3,
  40,
  15,
  6,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  2,
  6,
  16,
  5,
  13,
  'Yes',
  307.0),
 ('travel_frequently',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  1,
  5,
  11,
  4,
  1,
  'Yes',
  None),
 ('travel_rarely',
  'Unknown',
  5,
  ' manager ',
  'Unknown',
  0,
  2,
  36,
  4,
  13,
  'Yes',
  374.0),
 ('Unknown',
  'Unknown',
  4,
  ' manager ',
  'Unknown',
  0,
  2,
  22,
  0,
  4,
  'Yes',
  None),
 ('travel_rarely',
  ' Research & Development ',
  3,
  ' healthcare representative ',
  'No',
  3,
  5,
  18,
  3,
  7,
  'No',
  None),
 ('Unknown',
  'Unknown',
  3,
  ' research director ',
  'Unknown',
  1,
  3,
  11,
  2,
  9,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  4,
  ' research director ',
  'No',
  1,
  3,
  25,
  3,
  9,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  2,
  ' manufacturing director ',
  'No',
  1,
  5,
  13,
  3,
  12,
  'Yes',
  524.0),
 ('travel_rarely',
  ' Research & Development ',
  4,
  ' manager ',
  'No',
  1,
  2,
  27,
  15,
  7,
  'Yes',
  569.0),
 ('Unknown',
  'Unknown',
  3,
  ' manufacturing director ',
  'No',
  0,
  2,
  13,
  4,
  8,
  'No',
  899.0),
 ('Unknown',
  'Unknown',
  2,
  ' manufacturing director ',
  'Yes',
  0,
  3,
  19,
  2,
  7,
  'Yes',
  None),
 ('Unknown',
  ' Research & Development ',
  3,
  ' healthcare representative ',
  'Yes',
  1,
  3,
  16,
  10,
  1,
  'Yes',
  1014.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' healthcare representative ',
  'Unknown',
  1,
  6,
  11,
  11,
  1,
  'Yes',
  None),
 ('Unknown',
  ' Sales ',
  2,
  ' sales executive ',
  'Unknown',
  1,
  2,
  15,
  4,
  12,
  'No',
  1117.0),
 ('Unknown',
  ' Research & Development ',
  1,
  ' research scientist ',
  'Unknown',
  1,
  5,
  14,
  4,
  10,
  'No',
  1238.0),
 ('travel_frequently',
  'Unknown',
  1,
  ' research scientist ',
  'No',
  0,
  2,
  11,
  0,
  7,
  'No',
  None),
 ('Unknown', 'Unknown', 5, ' manager ', 'Yes', 0, 2, 24, 1, 11, 'Yes', 1277.0),
 ('travel_frequently',
  'Unknown',
  5,
  ' manager ',
  'Yes',
  1,
  5,
  29,
  11,
  10,
  'No',
  None),
 ('travel_rarely',
  'Unknown',
  1,
  ' sales representative ',
  'Yes',
  1,
  4,
  11,
  5,
  7,
  'No',
  1541.0),
 ('travel_rarely',
  ' Research & Development ',
  4,
  ' research director ',
  'No',
  1,
  3,
  14,
  6,
  11,
  'Yes',
  1666.0),
 ('Unknown',
  'Unknown',
  2,
  ' laboratory technician ',
  'No',
  1,
  3,
  15,
  4,
  13,
  'No',
  1696.0),
 ('Unknown',
  'Unknown',
  1,
  ' human resources ',
  'No',
  3,
  3,
  11,
  3,
  8,
  'Yes',
  1805.0),
 ('Unknown',
  'Unknown',
  5,
  ' research director ',
  'No',
  0,
  3,
  22,
  12,
  9,
  'No',
  None),
 ('Unknown',
  ' Research & Development ',
  2,
  ' research scientist ',
  'Yes',
  0,
  3,
  15,
  6,
  11,
  'No',
  1932.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' sales executive ',
  'No',
  2,
  3,
  14,
  5,
  7,
  'Yes',
  2016.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' manufacturing director ',
  'No',
  1,
  1,
  10,
  8,
  8,
  'No',
  20.0),
 ('Unknown',
  'Unknown',
  3,
  ' healthcare representative ',
  'Yes',
  1,
  5,
  10,
  9,
  5,
  'No',
  None),
 ('Unknown',
  ' Human Resources ',
  2,
  ' human resources ',
  'Yes',
  0,
  2,
  11,
  4,
  7,
  'No',
  184.0),
 ('Unknown',
  'Unknown',
  2,
  ' laboratory technician ',
  'No',
  1,
  2,
  17,
  0,
  15,
  'Yes',
  206.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' sales executive ',
  'No',
  1,
  2,
  10,
  7,
  4,
  'Yes',
  228.0),
 ('Unknown',
  'Unknown',
  2,
  ' laboratory technician ',
  'No',
  2,
  4,
  12,
  6,
  10,
  'Yes',
  239.0),
 ('travel_frequently',
  'Unknown',
  2,
  ' manufacturing director ',
  'Unknown',
  0,
  2,
  10,
  1,
  9,
  'No',
  256.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' research director ',
  'No',
  2,
  5,
  10,
  4,
  7,
  'No',
  None),
 ('Unknown',
  'Unknown',
  2,
  ' manufacturing director ',
  'Unknown',
  1,
  3,
  11,
  5,
  9,
  'Yes',
  339.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  2,
  3,
  11,
  6,
  9,
  'Yes',
  406.0),
 ('travel_frequently',
  'Unknown',
  3,
  ' laboratory technician ',
  'Unknown',
  1,
  2,
  24,
  9,
  11,
  'Yes',
  None),
 ('Unknown',
  'Unknown',
  4,
  ' manager ',
  'Unknown',
  0,
  3,
  21,
  11,
  10,
  'Yes',
  429.0),
 ('Unknown',
  'Unknown',
  3,
  ' manufacturing director ',
  'No',
  1,
  2,
  10,
  8,
  9,
  'No',
  None),
 ('Unknown',
  ' Research & Development ',
  5,
  ' manager ',
  'Unknown',
  1,
  2,
  21,
  13,
  3,
  'Yes',
  444.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' research scientist ',
  'No',
  2,
  3,
  10,
  9,
  8,
  'Yes',
  452.0),
 ('travel_rarely',
  ' Sales ',
  2,
  ' sales executive ',
  'Unknown',
  3,
  2,
  10,
  1,
  2,
  'Yes',
  456.0),
 ('Unknown',
  'Unknown',
  3,
  ' manufacturing director ',
  'Unknown',
  0,
  2,
  11,
  4,
  10,
  'No',
  None),
 ('Unknown',
  'Unknown',
  3,
  ' sales executive ',
  'No',
  1,
  2,
  13,
  1,
  12,
  'Yes',
  481.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  2,
  2,
  10,
  9,
  0,
  'Yes',
  513.0),
 ('travel_rarely',
  'Unknown',
  4,
  ' manager ',
  'No',
  0,
  2,
  10,
  7,
  7,
  'Yes',
  597.0),
 ('Unknown',
  'Unknown',
  2,
  ' sales executive ',
  'Unknown',
  0,
  2,
  11,
  6,
  9,
  'Yes',
  600.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' manufacturing director ',
  'Unknown',
  1,
  5,
  10,
  5,
  8,
  'No',
  None),
 ('travel_rarely',
  'Unknown',
  2,
  ' research scientist ',
  'Yes',
  2,
  3,
  10,
  6,
  9,
  'Yes',
  630.0),
 ('Unknown',
  'Unknown',
  5,
  ' research director ',
  'Yes',
  1,
  5,
  31,
  0,
  9,
  'Yes',
  638.0),
 ('travel_rarely',
  ' Research & Development ',
  1,
  ' research scientist ',
  'No',
  1,
  4,
  10,
  8,
  8,
  'Yes',
  683.0),
 ('travel_rarely',
  'Unknown',
  1,
  ' research scientist ',
  'Unknown',
  0,
  2,
  10,
  7,
  8,
  'No',
  780.0),
 ('Unknown',
  ' Research & Development ',
  3,
  ' research director ',
  'No',
  0,
  3,
  13,
  3,
  7,
  'Yes',
  817.0),
 ('travel_rarely',
  'Unknown',
  4,
  ' research director ',
  'No',
  0,
  0,
  12,
  3,
  8,
  'Yes',
  901.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' laboratory technician ',
  'Unknown',
  1,
  3,
  26,
  1,
  7,
  'No',
  944.0),
 ('Unknown',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  1,
  2,
  10,
  0,
  8,
  'No',
  984.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' healthcare representative ',
  'Unknown',
  1,
  4,
  19,
  1,
  9,
  'No',
  1088.0),
 ('Unknown', ' Sales ', 4, ' manager ', 'No', 1, 3, 12, 4, 9, 'No', 1124.0),
 ('non-travel',
  'Unknown',
  2,
  ' manufacturing director ',
  'Unknown',
  0,
  0,
  11,
  0,
  9,
  'No',
  None),
 ('travel_frequently',
  'Unknown',
  4,
  ' sales executive ',
  'Unknown',
  0,
  2,
  21,
  13,
  14,
  'Yes',
  1167.0),
 ('travel_frequently',
  'Unknown',
  2,
  ' healthcare representative ',
  'No',
  0,
  3,
  13,
  4,
  9,
  'Yes',
  1184.0),
 ('travel_rarely',
  ' Research & Development ',
  1,
  ' research scientist ',
  'Yes',
  1,
  2,
  11,
  5,
  7,
  'Yes',
  None),
 ('travel_rarely',
  'Unknown',
  4,
  ' research director ',
  'No',
  0,
  2,
  10,
  0,
  9,
  'Yes',
  None),
 ('travel_rarely',
  'Unknown',
  2,
  ' healthcare representative ',
  'No',
  0,
  2,
  10,
  1,
  8,
  'No',
  1252.0),
 ('Unknown', 'Unknown', 5, ' manager ', 'No', 1, 5, 22, 3, 10, 'Yes', 1267.0),
 ('non-travel',
  'Unknown',
  4,
  ' healthcare representative ',
  'Yes',
  1,
  3,
  33,
  15,
  0,
  'No',
  1278.0),
 ('travel_rarely',
  'Unknown',
  5,
  ' manager ',
  'No',
  2,
  4,
  25,
  14,
  13,
  'No',
  1288.0),
 ('travel_frequently',
  ' Human Resources ',
  2,
  ' human resources ',
  'No',
  2,
  5,
  10,
  1,
  8,
  'Yes',
  None),
 ('Unknown', 'Unknown', 4, ' manager ', 'Yes', 2, 4, 19, 15, 2, 'No', 1307.0),
 ('travel_rarely',
  'Unknown',
  5,
  ' manager ',
  'Unknown',
  1,
  5,
  19,
  9,
  11,
  'Yes',
  1336.0),
 ('Unknown',
  'Unknown',
  4,
  ' manager ',
  'Unknown',
  1,
  2,
  33,
  0,
  10,
  'Yes',
  1352.0),
 ('Unknown',
  'Unknown',
  3,
  ' manufacturing director ',
  'Unknown',
  0,
  0,
  10,
  5,
  9,
  'Yes',
  1360.0),
 ('Unknown',
  'Unknown',
  3,
  ' manufacturing director ',
  'No',
  0,
  2,
  10,
  0,
  8,
  'Yes',
  None),
 ('travel_rarely',
  ' Human Resources ',
  3,
  ' human resources ',
  'Unknown',
  0,
  3,
  10,
  0,
  9,
  'No',
  1419.0),
 ('Unknown',
  'Unknown',
  2,
  ' sales executive ',
  'No',
  0,
  2,
  13,
  3,
  12,
  'Yes',
  1478.0),
 ('travel_frequently',
  'Unknown',
  1,
  ' laboratory technician ',
  'Unknown',
  0,
  3,
  12,
  5,
  8,
  'Yes',
  1480.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' research scientist ',
  'No',
  1,
  2,
  12,
  2,
  8,
  'Yes',
  None),
 ('travel_rarely',
  'Unknown',
  2,
  ' sales executive ',
  'Yes',
  0,
  2,
  15,
  10,
  10,
  'No',
  1489.0),
 ('travel_frequently',
  'Unknown',
  4,
  ' manager ',
  'No',
  1,
  2,
  14,
  1,
  12,
  'Yes',
  1520.0),
 ('travel_rarely',
  'Unknown',
  3,
  ' sales executive ',
  'Unknown',
  0,
  3,
  10,
  8,
  6,
  'No',
  1535.0),
 ('Unknown',
  'Unknown',
  1,
  ' laboratory technician ',
  'Unknown',
  0,
  3,
  10,
  1,
  5,
  'Yes',
  1586.0),
 ('travel_rarely',
  'Unknown',
  2,
  ' laboratory technician ',
  'Unknown',
  2,
  3,
  10,
  6,
  8,
  'Yes',
  1596.0),
 ('Unknown',
  'Unknown',
  2,
  ' sales executive ',
  'Unknown',
  0,
  2,
  11,
  6,
  7,
  'Yes',
  1667.0),
 ('travel_rarely',
  'Unknown',
  1,
  ' research scientist ',
  'No',
  0,
  3,
  10,
  8,
  7,
  'Yes',
  1701.0),
 ('Unknown',
  'Unknown',
  2,
  ' sales executive ',
  'Yes',
  1,
  3,
  10,
  8,
  8,
  'No',
  1706.0),
 ('non-travel',
  'Unknown',
  4,
  ' manager ',
  'No',
  1,
  0,
  16,
  14,
  14,
  'Yes',
  None),
 ('travel_rarely',
  ' Sales ',
  2,
  ' sales executive ',
  'Yes',
  1,
  4,
  10,
  1,
  7,
  'No',
  None),
 ('travel_rarely',
  'Unknown',
  3,
  ' healthcare representative ',
  'Unknown',
  1,
  1,
  10,
  0,
  9,
  'Yes',
  1971.0),
 ('Unknown', 'Unknown', 5, ' manager ', 'Yes', 1, 0, 10, 1, 4, 'Yes', None),
 ('Unknown',
  ' Research & Development ',
  2,
  ' research scientist ',
  'Unknown',
  0,
  2,
  20,
  3,
  7,
  'Yes',
  1976.0),
 ('Unknown',
  'Unknown',
  2,
  ' laboratory technician ',
  'Unknown',
  1,
  2,
  10,
  9,
  4,
  'Yes',
  1985.0),
 ('Unknown',
  ' Research & Development ',
  1,
  ' laboratory technician ',
  'No',
  1,
  4,
  10,
  9,
  8,
  'Yes',
  2032.0),
 ('travel_rarely',
  'Unknown',
  4,

In [34]:
cnx = mysql.connector.connect(user = "root",
                              password = "AlumnaAdalab",
                              host = "127.0.0.1",
                              database = "abc_proyecto")#Nuesta base de datos de mysql
#Nos permite enviar informacion atraves de la conexciosm
mycursor = cnx.cursor()


#Escribimos la query aqui
#¡¡¡El ORDEN IMPORTA!!! --> El primer dato debe ser el primer elemento de la lista de tuplas
#sql_proyecto1 = "INSERT INTO salario (dailyrate, monthlyrate, percentsalaryhike, hourlyrate, employeenumber) VALUES (%s, %s, %s, %s,%s)" 
sql_proyecto = sql_proyecto = "INSERT INTO condiciones (businesstravel, department, joblevel, jobrole, overtime, stockoptionlevel, trainingtimeslastyear, yearsatcompany, yearssincelastpromotion, yearswithcurrmanager, remotework, employeenumber) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"



try:
    mycursor.executemany(sql_proyecto, lista_tuplas_condiciones)
    cnx.commit()
    print(mycursor.rowcount,"registros insertados")
except Exception as e:
    print("Ha habido un error en la inserción:", e)

1571 registros insertados